### ISSUE TITLE
제출 결과의 숫자 표시에 대한 케이스 정리

### ISSUE THREAD

**Issue by joonas-yoon** [joonas-yoon/boj-extended#106]
스크린샷 첨부해서 케이스 다시 정리

- `맞았습니다!! (00/00)` - AC, PAC  [(참고)](https://www.acmicpc.net/status?radio-extended=on&problem_id=20166&user_id=&language_id=-1&result_id=4&from_problem=1)
- - ![image](https://user-images.githubusercontent.com/9527681/185736997-cc25abed-e7eb-42ed-8950-e856e289db11.png)
- ~`맞았습니다!! (00점)` - AC [(참고)](https://www.acmicpc.net/status?radio-extended=on&problem_id=10946&user_id=&language_id=-1&result_id=4&from_problem=1)~ => 사라짐
- `00점` - AC, PAC [(참고)](https://www.acmicpc.net/status?radio-extended=on&problem_id=3090&user_id=&language_id=-1&result_id=4&from_problem=1)
- - ![image](https://user-images.githubusercontent.com/9527681/185736930-1b39c9c7-8a90-4fad-a87f-4646f3f8bea4.png) ![image](https://user-images.githubusercontent.com/9527681/185737057-e3928e00-2e55-4789-a8ec-6f3fa897b280.png)
- `채점중 (00%)` - JUDGING
- - ![image](https://user-images.githubusercontent.com/9527681/185737121-647f4cea-08fd-48f1-8042-1dc86d297481.png)
- `틀렸습니다 [4]` - WA [(참고)](https://www.acmicpc.net/status?radio-extended=on&problem_id=17690&user_id=&language_id=-1&result_id=6&from_problem=1)
- - ![image](https://user-images.githubusercontent.com/9527681/185736912-e4bbb431-cdcb-48bf-91a7-338fb280c46a.png)

**Comment by getCurrentThread** [comment]
다른 익스텐션에서 사용한 케이스 공유 드립니다. :)

```
/* 채점 결과에 대한 각 구분 정보 */
const RESULT_CATEGORY = {
  RESULT_PENDING: 'wait',
  RESULT_PENDING_REJUDGE: 'rejudge-wait',
  RESULT_NO_JUDGE: 'no-judge',
  RESULT_PREPARE_FOR_JUDGE: 'compile',
  RESULT_JUDGING: 'judging',
  RESULT_ACCEPTED: 'ac',
  RESULT_PARTIALLY_ACCEPTED: 'pac',
  RESULT_PRESENTATION_ERROR: 'pe',
  RESULT_WRONG_ANSWER: 'wa',
  RESULT_ACCEPTED_NOT_CORRECT: 'awa',
  RESULT_TIME_LIMIT_EXCEEDED: 'tle',
  RESULT_MEMORY_LIMIT_EXCEEDED: 'mle',
  RESULT_OUTPUT_LIMIT_EXCEEDED: 'ole',
  RESULT_RUNTIME_ERROR: 'rte',
  RESULT_COMPILATION_ERROR: 'ce',
  RESULT_UNVAILABLE: 'co',
  RESULT_DELETED: 'del',
};

/* 채점 결과에 대한 각 메시지 구분 맵핑 */
const RESULT_MESSAGE = {
  [RESULT_CATEGORY.RESULT_PENDING]: '기다리는 중',
  [RESULT_CATEGORY.RESULT_PENDING_REJUDGE]: '재채점을 기다리는 중',
  [RESULT_CATEGORY.RESULT_NO_JUDGE]: '채점하지 않음',
  [RESULT_CATEGORY.RESULT_PREPARE_FOR_JUDGE]: '채점 준비 중',
  [RESULT_CATEGORY.RESULT_JUDGING]: '채점 중',
  [RESULT_CATEGORY.RESULT_ACCEPTED]: '맞았습니다!!',
  [RESULT_CATEGORY.RESULT_PARTIALLY_ACCEPTED]: '맞았습니다!!',
  [RESULT_CATEGORY.RESULT_PRESENTATION_ERROR]: '출력 형식이 잘못되었습니다',
  [RESULT_CATEGORY.RESULT_WRONG_ANSWER]: '틀렸습니다',
  [RESULT_CATEGORY.RESULT_ACCEPTED_NOT_CORRECT]: '!맞았습니다',
  [RESULT_CATEGORY.RESULT_TIME_LIMIT_EXCEEDED]: '시간 초과',
  [RESULT_CATEGORY.RESULT_MEMORY_LIMIT_EXCEEDED]: '메모리 초과',
  [RESULT_CATEGORY.RESULT_OUTPUT_LIMIT_EXCEEDED]: '출력 초과',
  [RESULT_CATEGORY.RESULT_RUNTIME_ERROR]: '런타임 에러',
};
```

**Comment by getCurrentThread** [comment]
[백준 사이트 채점 현황 페이지](https://www.acmicpc.net/status)에 있는 [result.css](https://ddo7jzca0m2vt.cloudfront.net/css/result.css?version=20220413)를 참고하시면 좋더군요.

매칭이 덜 된 케이스나 영문으로된 것도 전부 아래 하단에 표기되어 있습니다.

**Comment by joonas-yoon** [comment]
감사합니다 CSS가 변경이 있었군요.


.result-awa-text 케이스는 혹시 무슨 경우인 지 아시나요?

________________________________

**Comment by getCurrentThread** [comment]
@joonas-yoon 
이전에 보았던 내용상으로는 재채점으로 인하여 맞은 결과가 뒤집히면 awa로 들어가는 것으로 알고 있었습니다만,,,

지금 그 관련 문서나 채점 현황에서 awa로 되어 있는 것이 없고, 
재채점으로도 이제는 바뀐 결과를 보여주는 것으로 되어서 사용된 흔적을 찾아보기 힘드네요.
(= 추측일 뿐 근거를 못찾겠네요 )

무시하셔도 될 것 같습니다. 😢

**Comment by joonas-yoon** [comment]
코멘트 감사합니다 ㅎㅎ 저도 버그를 하나 찾았는데 관련해서 조만간 리팩토링을 한번 싹 해야겠네요
