### ISSUE TITLE
Electron에서 의 버튼 & 타이머 오작동

### ISSUE THREAD

**Issue by smartwe** [joonas-yoon/boj-extended#107]
### What happens

<img width="1509" alt="스크린샷 2022-08-20 20 55 23" src="https://user-images.githubusercontent.com/73765768/185745066-fc3c3def-3762-408d-a4f2-ed3df73ca1da.png">

### Operating System

macOS

### 확장 프로그램 버전

1.8.3.1

### 콘솔
```js
problem.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at HTMLFormElement.<anonymous> (problem.js:1:1900)
```

**Comment by joonas-yoon** [comment]
먼저 확인이 필요한 것이 있습니다.

코드를 그대로 사용하시면 브라우저에 따라 호환되지 않을 가능성이 높습니다. `npm run build` 명령어를 통해 생성된 `dist` 하위 디렉토리의 코드로 실행을 확인하셔야합니다.

두번째로는, Electron은 BOJ Extended에서 타겟으로 하지 않는 환경입니다. https://caniuse.com/?search=classlist 를 통해서 브라우저와 해당 method의 호환 여부를 확인해주세요.

**Comment by joonas-yoon** [comment]
빌드와 관련해서는 README를 참고해주세요.

https://github.com/joonas-yoon/boj-extended#build
