### ISSUE TITLE
제출 페이지에서 소스코드를 컴파일할 수 있는 기능

### ISSUE THREAD

**Issue by smartwe** [joonas-yoon/boj-extended#110]
### 내용

```markdown
소스를 바로바로 컴파일하면서 테스트케이스와 일치하는지 확인하면 편하지 않을까요??
```

**Comment by joonas-yoon** [comment]
아이디어 제안 감사합니다.

하지만 이건 브라우저 익스텐션에서 감당하기엔 큰 역할입니다. 특히 BOJ의 경우 지원하는 언어가 수십개에 이르기때문에, 그것을 모두 각 유저의 로컬에서 지원하기란 불가능에 가깝습니다.
별도의 컴파일 머신을 원격에서 돌리는 것 역시 투머치이며 불필요합니다. 이미 PaaS나 SaaS 형태로 잘 제공되고 있는 WebIDE들(repl.it, ideone.com 등)을 사용하는 것이 맞아 보입니다.

참고로, 문제 풀이 사이트의 예제를 로컬에서 채점해볼 수 있는 VS Code Extension으로 CPH라고 있더군요. 한번 참고해보시면 좋을 것 같습니다.
https://marketplace.visualstudio.com/items?itemName=DivyanshuAgrawal.competitive-programming-helper
