### ISSUE TITLE
광고 차단(adblock) 기능

### ISSUE THREAD

**Issue by smartwe** [joonas-yoon/boj-extended#111]
### 내용

```markdown
음 이미 adblock 프로그램을 가지고 있지 않아도 확장하나로 광고차단을 하면 편할 것 같습니다
```

**Comment by joonas-yoon** [comment]
아이디어 등록해주셔서 감사합니다 :)

광고 차단을 원하시는 분은 adblock을 설치하시는 게 맞아보이고, 높은 확률로 설치하셨으리라 생각합니다.

그리고 BOJ 운영에 지장을 줄 수 있는 광고 차단 등의 기능은 구현하지 않을 계획입니다.
