### ISSUE TITLE
빠른 검색 오류

### ISSUE THREAD

**Issue by kbk0421** [joonas-yoon/boj-extended#113]
### What happens

```markdown
alt + tab으로 백준 페이지로 이동한 경우
alt키를 누르지 않아도 /를 누르면 빠른 검색창이 나오는 것 같네요
(alt + tab 말고도 ctrl + tab 같은 단축기를 사용하고 난 뒤에
/를 눌러도 빠른 검색창이 나오는 것 같아요)
```

### Operating System

Windows

### 환경

 - OS: 10.0.19043.0
 - Architecture: X64

### 확장 프로그램 버전

1.8.4

**Comment by joonas-yoon** [comment]
제보 감사합니다. `ctrl + tab` 은 확인하지 못했는데, `alt + tab` 이후 `/` 은 말씀하신대로 버그가 그대로 발생하네요.

현상 확인해보고 업데이트 하도록 하겠습니다 :)

**Comment by joonas-yoon** [comment]
안녕하세요, 이슈의 원인은 `ctrl` 또는 `alt`를 누른 채로 윈도우를 이동하게 되면, 다시 돌아왔을 때 `ctrl` 또는 `alt`가 계속 눌러져있는 것으로 인식되는 것이 원인이었습니다.

해결 방법으로는 `ctrl` 이나 `alt`를 한번 눌러주면 해당 키가 떼어지면서 해결이 됩니다.

프로그래밍적으로 어떻게 고칠 수 있을지는 계속 고민을 해보겠습니다.

**Comment by joonas-yoon** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus

**Comment by joonas-yoon** [comment]
@kbk0421 버그가 수정되었고, 1.8.4.1 버전으로 배포되었습니다! 🎉🎉 제보 감사합니다.
