### ISSUE TITLE
유저 티어 표시 기능 오류

### ISSUE THREAD

**Issue by C792** [joonas-yoon/boj-extended#122]
**일시적으로** 기능 중 유저 티어 보기 기능에서 티어가 전부 알 수 없음으로 뜨는 오류가 있습니다.

Chrome 콘솔에서는
Failed to load resource: the server responded with a status of 429 ()
라고 하네요

Windows 11 Chrome 106.0.5249.119 버전을 사용하고 있습니다.

확장 프로그램 버전은 v1.9.1 입니다

![image](https://user-images.githubusercontent.com/89120533/195974923-d9797117-58c1-4ecf-99b2-67d194ac13e9.png)
![image](https://user-images.githubusercontent.com/89120533/195975311-dd939d5c-53a4-42d1-8f04-0a679b62b703.png)
![image](https://user-images.githubusercontent.com/89120533/195975274-8c6eafbb-fa55-4928-9fff-f601ae3d0445.png)

![image](https://user-images.githubusercontent.com/89120533/195974947-1318e918-4943-4424-9060-6966c17b22b1.png)

**Comment by joonas-yoon** [comment]
안녕하세요 :)

해당 이슈는 solved.ac API에 초당 요청 제한이 문제였던 걸로 기억합니다. BOJ Extended를 위한 별도의 프록시 서버를 운영할 계획은 아직 없어서 여러 가지 방법을 시도해보려고 합니다.

1.9.2 버전에서 문제가 해소될 수 있도록 해보겠습니다. 업데이트는 여기에 남기도록 할게요 :)

제보 감사합니다.

**Comment by joonas-yoon** [comment]
버그를 수정하여 1.9.2 버전으로 배포하였습니다 😃

여전히 발생할 수 있으나 반복적으로 발생하지는 않을 것으로 예상됩니다, 감사합니다.
