### ISSUE TITLE
채점 현황에서 문제 이름과 함께 문제 번호를 보여주는 기능

### ISSUE THREAD

**Issue by VertexToEdge** [joonas-yoon/boj-extended#124]
### 내용

https://user-images.githubusercontent.com/37045096/196042596-54ac96c5-f885-4b1a-b14f-8d950bec17f7.mp4

<img width="568" alt="image" src="https://user-images.githubusercontent.com/37045096/196041548-ad77e19e-d12c-49b2-9a80-d3a0e1e0fe44.png">

학교 알고리즘 동아리에서 문제 해결 현황을 공유하는데 문제명과 아이디가 함께 표시되면 가독성에 도움이 될 것 같아서 fork 후 해당 기능을 구현하였습니다.

혹시 PR을 보내도 될까요??

**Comment by joonas-yoon** [comment]
오 너무 좋네요 ㅎㅎㅎ PR 올려주시면 리뷰하겠습니다!
