### ISSUE TITLE
프로필 페이지의 CSS 비활성화 기능

### ISSUE THREAD

**Issue by WondooSeo** [joonas-yoon/boj-extended#127]
### 내용

```markdown
아마도 모든 문제를 불러와서 거기에 모든 티어를 붙이고 제목 붙이는 작업 때문에 그런거 같은데, 이게 꽤 로딩이 심하게 걸려서 렉이 걸릴 때도 있습니다.

첫 100문제만 불러와서 보여주고, 더 보고 싶으면 더 보기를 누르는 방식으로 로딩 시간을 줄여줬으면 좋겠습니다.
```

**Comment by joonas-yoon** [comment]
![](https://raw.githubusercontent.com/joonas-yoon/boj-extended/main/docs/images/screenshot-user.png)

1.8.3 버전부터 첫 100문제와 더보기 버튼을 표시하고 있는데 사용하고 계신 확장 프로그램의 버전이 어떻게 되나요?

그리고 프로필 페이지에 모든 문제를 불러오는 것은 확장 프로그램의 영역 밖인, BOJ 사이트에서 렌더링되는 부분이기 때문에 로딩 페이지를 개선하는 데 한계가 있습니다.
확장 프로그램을 비활성화한 이후에 캐싱 새로고침(ctrl+shift+R)을 하셔도 동일하게 페이지가 느리게 로딩되는 지 확인 부탁드립니다.

**Comment by WondooSeo** [comment]
답변 주셔서 감사합니다.

현재 제가 쓰고 있는 버전은 최신버전(1.9.3)이고, 첫 100개 문제 이외의 다른 해결된 문제까지 모두 티어가 매겨지는 동작으로 인해 조금 느려진 것이 아닌가 싶은 생각이 들어 이슈탭을 열었습니다. 한번 불러와진 경우엔 캐시가 있어서 그런지 다음에 불러올 때는 바로 페이지가 로딩 없이 열리는 것을 확인했습니다.

일단 확장 프로그램이 없는 경우에는 빠르게 불러와지는 것을 확인했습니다.

혹시 제가 추가로 더 알려드려야 할 사항이 있다면 알려주시면 감사하겠습니다.

**Comment by joonas-yoon** [comment]
페이지 최초 로드 이후에는 브라우저 캐싱과 별도로 로컬 스토리지에 저장해서 다시 불러올 때 갱신 주기를 미루고 있습니다.
로컬 스토리지도 매번 접근하는 건 아니고 backgroundㅔ서 메모리로 들고 있기는 합니다.

문제 정보를 전부 기다리지는 않고, 문제를 100개씩 묶어서 제목, 번호, 티어를 넣어주는 형태라 딜레이가 얼마나 생기는 지 파악하기가 조금 어렵네요.

최근에 1.9.1 버전 업데이트에서 DOM 트리 조작을 줄이고 CSS를 사용해서 속도를 높이는 작업을 하긴 했었습니다.

아무래도 페이지에서 일어나는 변경이 좀 크다보니 로컬 컴퓨터의 성능에 따라 많이 다를 것 같습니다. 옵션으로 저성능 모드를 구현하는 것도 고려해보겠습니다.

**Comment by WondooSeo** [comment]
네 감사합니다.

**Comment by joonas-yoon** [comment]
CSS 렌더링 시간을 측정해보니까 매번 캐시를 지우고 로드하면 평균적 1288ms 정도 걸리네요.

캐싱 이후로는 430ms 이하까지 줄어드는 걸 확인했는데, "문제 제목"을 표기하는 것 자체에 DOM 조작이 들어가서 CSS 업데이트보다 이것이 더 차이를 일으키는 것 같습니다.

모듈 내부에 if 케이스가 생각보다 큰 덩어리로 생기는 것 같아서, 우선은 구현을 보류하고 추후에 전체적으로 저성능 모드를 구현할 때 해보도록 하겠습니다.

이슈는 우선 닫아두로록 하겠습니다. 리포트 해주셔서 감사합니다 :)
