### ISSUE TITLE
BOJ Stack에서 제출 버튼을 누르면 test 메뉴로 이동

### ISSUE THREAD

**Issue by kiwiyou** [joonas-yoon/boj-extended#128]
### 내용

```markdown
BOJ Stack에서 문제 본문을 확인할 때에는 제출 버튼이 아무 동작도 하지 않습니다. BOJ Stack에서 제출 버튼을 눌렀을 때 문제 테스트 페이지로 이동해서 코드를 바로 제출할 수 있도록 하면 좋겠습니다.
```

**Comment by joonas-yoon** [comment]
확장 프로그램이 없는 상태에서도, BOJ Stack에서 문제를 미리보기 하는 경우에는 어떤 버튼도 동작하지 않는 것으로 보입니다.

문제를 보는 화면의 주소가 stack.acmicpc.net 인지 확인 부탁드립니다.

**Comment by kiwiyou** [comment]
BOJ Stakc에서 문제를 미리보기 하는 경우에 버튼이 동작하지 않는 것이 정상이고, BOJ Extended를 통해 제출 버튼을 테스트 메뉴로 이동하도록 변경하는 기능을 추가 건의하려고 합니다.

**Comment by joonas-yoon** [comment]
아하 새로운 기능을 요청하신거였군요 ㅎㅎ

BOJ Stack의 일부 기능들이 접근하는 조건이 쉽지가 않아서.. 아쉽지만 Stack 사이트까지 커버하기엔 어려워보입니다.

이번에 작성해주신 이슈도, 전에 제가 출제했던 문제가 있어서 확인할 수 있었던 내용이에요.

**Comment by kiwiyou** [comment]
요청한 기능만을 추가하는 것이 어려울까요? 가능하다면 저도 기여하고 싶습니다.

**Comment by joonas-yoon** [comment]
넵 물론이죠! 이 repository를 fork 하신 후에 Pull Request로 올려주시면 리뷰하도록 하겠습니다.

그리고 `stack.acmicpc.net`을 `manifest.json`에 추가해주셔야 해당 사이트에서도 확장 프로그램이 동작할 수 있으니 참고해주세요 :)

https://github.com/joonas-yoon/boj-extended/blob/304692bbf1636e51f843a7f17128844fd837a014/manifest.json#L77-L80

걱정되는 건, `stack.acmicpc.net` 사이트를 추가했을 때 어떤 문제가 생길 지 모르겠네요 ㅎㅎ;

**Comment by joonas-yoon** [comment]
이슈는 invalid로 닫도록 하겠습니다. 하지만 Pull Request는 가능하니까 언제든 기다리겠습니다 ㅎㅎ :)
