### ISSUE TITLE
유저 티어 기능 오류

### ISSUE THREAD

**Issue by w8385** [joonas-yoon/boj-extended#129]
### What happens

```markdown
유저의 실제 solved.ac 티어가 랭킹화면 및 상단탭에서 정상적으로 보이지 않습니다.
```

### Operating System

Windows

### 환경

 - OS: 10.0.22622.0
  - Architecture: X64

### 확장 프로그램 버전

1.9.3

**Comment by w8385** [comment]
![image](https://user-images.githubusercontent.com/52066828/202917564-c86b12bf-8bb9-49f2-8468-567126e774a3.png)

**Comment by w8385** [comment]
![image](https://user-images.githubusercontent.com/52066828/202917583-b4bd1763-b65a-4d94-8422-bf65239d88bb.png)

**Comment by w8385** [comment]
![image](https://user-images.githubusercontent.com/52066828/202917813-2ae1ddb9-edda-4c25-86c5-d77638609c56.png)
구글 콘솔 오류는 위와 같습니다.

C792님의 #122 와 유사한 것 같습니다!

**Comment by joonas-yoon** [comment]
@w8385 님 안녕하세요. 자세한 버그 리포트 정말 감사합니다!

유저 티어는 solved.ac 에서 가져오고 있는데요, API 호출 횟수 제한으로 한번씩 실패하는 경우가 있더라구요.
혹시 새로고침을 해도 계속 발생하는 오류인가요? 그리고 24시간이 지나도 여전히 오류가 발생하는 지 알려주시면 감사하겠습니다.

**Comment by w8385** [comment]
네, 새로고침 및 컴퓨터 재부팅 이후에도 발생합니다!
아래 방금 캡처한 사진에서도 동일한 랭커분들의 티어가 인식되지 않습니다.
![image](https://user-images.githubusercontent.com/52066828/203010248-8116b890-2cfd-4fc3-8e6b-b8aff7b8b144.png)

제 로컬 캐시의 문제도 의심이 되어서, 캐시를 한번 지워보고 다시 말씀드리겠습니다 ;)

**Comment by w8385** [comment]
지금 다시 접속해보니 정상적으로 티어이미지를 불러옵니다!
(3위 분은 unrated가 맞습니다.)

이슈 닫도록 하겠습니다.
좋은 플러그인 개발과 빠른 이슈확인에 감사드립니다 :)
![image](https://user-images.githubusercontent.com/52066828/203056641-7d22d9d9-a56e-42e1-9660-980cbffe5c55.png)

**Comment by joonas-yoon** [comment]
넵.. 문제는 해결되어서 다행이지만, 여전히 브라우저의 로컬 캐시 문제가 맞는 지 확실하지가 않네요.
저도 같은 이유를 만나면 여기에 올려주셨던 정보를 많이 참고하겠습니다. 정말 감사합니다 ㅎㅎ
