### ISSUE TITLE
chrome에서 문제 퍼센트가 정상적으로 기록되지 않는 문제.

### ISSUE THREAD

**Issue by juwkim** [joonas-yoon/boj-extended#130]
### What happens

아래 크롬에서는 틀렸습니다에 문제 %가 기록되지 않습니다.
![20221204_020905](https://user-images.githubusercontent.com/66457470/205453030-0a28d207-31fc-441f-9d04-c9b5b667d2f2.png)

하지만 마이크로소프트 엣지로 실행한 결과 정상적으로 기록됩니다.
![20221204_021209](https://user-images.githubusercontent.com/66457470/205453141-f56c5fb6-b23b-4c24-a0e4-46f998e228fd.png)

### Operating System

Windows

### 환경

 OS: 10.0.19044.0
 Architecture: X64

### 확장 프로그램 버전

1.9.3

**Comment by joonas-yoon** [comment]
안녕하세요, 작성해주신 내용과 스크린샷 상으로는 52357824번 제출의 % 기록에 대해 말하시는거죠?

먼저, 두 브라우저 사이에서 제출 퍼센티지는 공유되지 않고 있습니다. [Window.localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)를 사용하고 있어서요.

Edge에서 제출하셨고 `(2%)`가 기록되었는 데, Chrome으로 접속한 채점현황에서 `(2%)`가 표시되지 않는 문제라면 버그로 보이지는 않습니다.

이 외에도 브라우저 간의 동기화는 별도로 관리하고 있지 않습니다. 로그인한 같은 브라우저를 사용한다면 설정값은 동기화를 하고 있습니다.

**Comment by joonas-yoon** [comment]
해당 이슈는 inactivity로 닫도록 하겠습니다 :)
