### ISSUE TITLE
Readme.md에 사파리는 dmg파일을 다운받으라고 하셧는데 어디에 있는지 모르겠습니다.

### ISSUE THREAD

**Issue by dlrjs2360** [joonas-yoon/boj-extended#131]
### What happens

```markdown
사파리는 플러그인을 빌드하기 까다로워서 아직 안하셧다는 글까지 읽어봤는데
혹시 아직 사파리는 지원하지 않는 걸까요??
아니면 제가 파일을 못찾고 있는 걸까요?
```

### Operating System

macOS

### 확장 프로그램 버전

사파리라서..

**Comment by joonas-yoon** [comment]
안녕하세요, 최근에 파일을 정리하면서 같이 삭제되었었네요. 아래 링크로 다시 업로드하였습니다.

https://github.com/joonas-yoon/boj-extended/releases/download/v1.5.8/boj-extended-for-safari-1.5.3.dmg

dmg로 변환한 파일이 1.5.3 버전임에 참고 부탁드립니다.

그리고 BOJ Extend 1.7.6 버전부터 Manifest V3를 사용하고 있어서, dmg 파일로 변환하더라도 Apple Safari 15.4 이하 버전에서는 동작하지 않을 수 있습니다.

**Comment by dlrjs2360** [comment]
감사합니다~~!
윈도우부터 정말 잘쓰고 있어요.
저는 백엔드이지만 yoon님 같은 항상 사랑받는 서비스를 개발하는 게 목표입니다.
항상 기억하고 응원하겠습니다~!

-----Original Message-----

**Comment by joonas-yoon** [comment]
말씀 정말 감사합니다 ^^
