### ISSUE TITLE
코드 에디터의 기본 색상 변경

### ISSUE THREAD

**Issue by joonas-yoon** [joonas-yoon/boj-extended#135]
> [on Dec 25, 2022](https://github.com/joonas-yoon/boj-extended/discussions/95#discussioncomment-4492365)
>
> @Risk-boy
> 안녕하세요 다크모드 잘 쓰고있습니다 ㅎㅎ 정말 감사해요! 테마 관련해서 한가지 건의사항이 있어서 댓글 남겨요. 저는 백준에서 파이썬을 주로 사용하는데요. 문제에 대한 코드를 제출 후에 또는 다른 유저들의 파이썬 코드를 볼때 남색으로 나타나는 부분이 있더라구요. 남색이 정말 안보여요!! 그래서 혹시 파이썬에 대한 테마만 변경해 주실 수 있으신가용? 감사합니다~!
>

> @joonas-yoon
> 안녕하세요 반갑습니다. 테마는 백준에서 제공하는 테마 중에 어두운 걸 제가 기본값으로 변경하는 정도만 했었어요.
> 글만으로는 어떤 부분이 말하시는 건지 파악하기가 어려운데 혹시 스크린샷을 여기에 올려주실 수 있을까요? ㅎㅎ
>
> @Risk-boy
> 오 안녕하세요 ㅎㅎ 캡쳐한거 보내드려요  range len sum abs 등 빌트인 함수들에대해서 남색이 적용되는 거 같아요 ㅠㅠ
> 육안으로 잘 안보이더라구요!
>

> @joonas-yoon
> 아 찾았어요, 이거 말씀하신거군요 ㅎㅎㅎ Base16 Default Dark 테마를 사용하고 있었는데, [Dracular](https://github.com/zenorocha/dracula-theme) 로 변경해보겠습니다 ㅎㅎ
> 
> ![mock](https://user-images.githubusercontent.com/9527681/209457077-74632180-ca75-472a-b54f-40ad54d62090.png)
>
> @Risk-boy
> 넵넵 저부분이에요 ㅎㅎ 감사합니다!!

**Comment by joonas-yoon** [comment]
아래와 같이 업데이트 했습니다.

![image](https://user-images.githubusercontent.com/9527681/216846218-538f3481-7f8d-4361-a6c6-21b4a66c0586.png)

요즘 바빠서 변경을 못 했었네요 😢 다음 버전에 반영하도록 하겠습니다!

**Comment by Risk-boy** [comment]
고생이 많으시네요 ㅎㅎ 감사합니다!!! :)

2023년 2월 6일 (월) 오전 6:15, Joona Yoon ***@***.***>님이 작성:
