### ISSUE TITLE
유저페이지

### ISSUE THREAD

**Issue by jjthis** [joonas-yoon/boj-extended#137]
문제를 많이 해결 한 분들의 프로필(https://www.acmicpc.net/user/)에 들어가면 로딩이 너무 느려서 시간이 많이 뺏깁니다. on/off 기능을 추가해 주세요.

**Comment by joonas-yoon** [comment]
제가 전에 기록했을때 2000문제가 있는 페이지를 기준으로  1~3초 정도 더 걸리긴했는데요 (Lighthouse 로 성능 측정)

확장 프로그램이 없더라도 문제가 많으면 페이지 자체 로드부터 오래 걸리긴 했었습니다.
확장 프로그램을 비활성화하시고 같은 페이지를 강제 새로고침 (`ctrl+shift+R`) 하더라도 오래 걸리는 지 확인해주실수 있을까요?

**Comment by joonas-yoon** [comment]
Duplicate #127

**Comment by joonas-yoon** [comment]
Closed by inactive
