### ISSUE TITLE
solved.ac 관련 기능이 동작하지 않음

### ISSUE THREAD

**Issue by GyuHo123** [joonas-yoon/boj-extended#138]
### What happens

```markdown
Microsoft Edge에서 BOJ Extended를 사용했을 때 유저페이지에서 맞은 문제의 난이도가 정상적으로 표시되지 않습니다.
```

![스크린샷 2023-03-07 204608](https://user-images.githubusercontent.com/74482513/223415151-5e8df528-39d4-4f90-8e96-7d615fda110d.png)

```markdown
Microsoft Edge에서 백준 메인페이지에 들어갔을 때 유저 닉네임 옆의 Solved.ac 티어가 정상적으로 표시되지 않습니다.
```
![스크린샷 2023-03-07 205844](https://user-images.githubusercontent.com/74482513/223415846-c5d6f180-2aa6-42b4-acd4-9798e9b55a27.png)

### Operating System

Windows

### 환경

- OS : 10.0.22621.0
- Architecture: X64

### 확장 프로그램 버전

1.9.3.1

**Comment by joonas-yoon** [comment]
공지글은 아직은 별도로 없지만, 2개월 전 공지글로 미루어보아 (https://www.acmicpc.net/board/view/107146)

서버에 CORS가 적용된 것으로 보입니다.

확장 프로그램에서 https://www.acmicpc.net/ 로 요청을 보내기때문에, same origin으로 허용될 지는 모르겠지만 우선은 제가 별도의 프록시 서버를 운영하지 않는 이상 해결하기 어려워보입니다.

크롤링은 최소로 하고 싶은데, 공식 API가 안내되기 전까지 다른 방법이 있는 지는 고민해보겠습니다.

**Comment by GyuHo123** [comment]
<https://ducks228.tistory.com/entry/%ED%81%AC%EB%A1%AC-%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-cors-disableenable>

위의 페이지에서 제시된 방법을 따라해보니 Chrome 브라우저에서 solved.ac 관련 기능 일부가 작동하는 것을 확인했습니다.

### 유저페이지 내부 맞은 문제
![image](https://user-images.githubusercontent.com/74482513/224215607-2f344dcc-fa2a-48cf-9417-83adbc89578a.png)

### 백준 메인페이지 유저 랭크 표시
![image](https://user-images.githubusercontent.com/74482513/224215773-b8ffb54c-6ce0-4524-b825-ff593a902dac.png)

### 랭킹 페이지
![image](https://user-images.githubusercontent.com/74482513/224216091-fa945717-b28d-475a-a221-57c3daa0161b.png)

**Comment by joonas-yoon** [comment]
아.. 네 공유 감사합니다.

이거는 제가 개발환경에서 사용하는 Chrome option 인데, 브라우저에 명시된대로 **안정성과 보안에 문제가 발생**합니다. 즉, 브라우저의 CORS 정책을 무력화시켜서 동작이 가능하도록 한 것은 정상적인 행위는 아닙니다.

위 내용을 인지하고 해당 기능을 활성화하고 싶으신 분들은 이 이슈 내용이 도움이 될 수 있겠네요 :)

**Comment by smartwe** [comment]
https://github.com/solvedac/unofficial-documentation/issues/51

**Comment by C792** [comment]
![image](https://user-images.githubusercontent.com/89120533/226876303-fbed22a2-f488-421a-8b6c-5cbd50ec08b4.png)
![image](https://user-images.githubusercontent.com/89120533/226876678-f9ba03cb-52cb-44c2-a205-a0b2d34b8a6f.png)
저도 요근래 기능이 거의 다 작동하지 않아서 잠시 지우고 며칠 있다 다시 설치해봤는데도 그대로네요..
Chrome 사용중입니다

**Comment by tpwls6630** [comment]
다른 곳에선 해결한 듯 합니다.
혹시 도움이 되실까 적어봅니다.

https://github.com/BaekjoonHub/BaekjoonHub/issues/185

https://github.com/BaekjoonHub/BaekjoonHub/commit/131693b34f9fb3cddfbf870886f19eac5c8779e3

**Comment by joonas-yoon** [comment]
> 

감사합니다. https://github.com/BaekjoonHub/BaekjoonHub/pull/183 참고해서 업데이트 진행해보겠습니다.

**Comment by joonas-yoon** [comment]
@tpwls6630 감사합니다. 알려주신 덕분에 생각보다 간단하게 해결할 수 있었습니다 :)

이 이슈는 1.9.4.1 버전에서 해결되어 배포될 예정입니다. 감사합니다.
