### ISSUE TITLE
Solved.ac 랭크가 모두 보이지 않는 버그

### ISSUE THREAD

**Issue by smartwe** [joonas-yoon/boj-extended#139]
### What happens

```markdown
개발자도구 - 콘솔 
Access to fetch at 'https://solved.ac/api/v3/user/show?handle=subinium' from origin 'https://www.acmicpc.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
https://user-images.githubusercontent.com/73765768/223431826-1312550e-c853-4033-b478-4d58e638a870.mp4

### Operating System

macOS

### 환경

실행했는데 개인정보가 너무 많이 나와서 못 올리겠네요 죄송합니다

### 확장 프로그램 버전

1.9.3.1

**Comment by joonas-yoon** [comment]
자세한 리포트 감사합니다. 아래 이슈와 같이 처리하도록 하겠습니다.

Closed as duplicate https://github.com/joonas-yoon/boj-extended/issues/138

**Comment by smartwe** [comment]
음? 다른거 같은데요?

**Comment by smartwe** [comment]
저는 모든 페이지에서 몇몇 유저를 제외한 유저의 랭크가 로딩이 안됩니다

**Comment by smartwe** [comment]
음.. 아니면 저분도 전체적으로 같은 증상인걸까요?
