### ISSUE TITLE
BOJ Extended 설정에서 유저 티어 설정이 불가능

### ISSUE THREAD

**Issue by smartwe** [joonas-yoon/boj-extended#140]
### What happens

<img width="285" alt="image" src="https://user-images.githubusercontent.com/73765768/223435099-e4d103ed-76c7-4f2f-83fe-42372fdf85ea.png">

### Operating System

macOS

### 확장 프로그램 버전

1.9.3.1

**Comment by smartwe** [comment]
클릭해서 창을 닫으면 설정이 저장이 안됩니다.

**Comment by joonas-yoon** [comment]
맙소사. 0/1을 반대로 표기하고 있네요.

보이는 것과 달리 동작은 정상적으로 되고 있습니다. 1.9.3.1 버전을 기준으로 아래처럼 적용할 수 있습니다.

1. 티어를 보는 법 : `보지 않기` 선택 후, 다시 `보기` 선택
2. 티어를 보지 않는 법 : `보지 않기` 선택

이건 바로 수정했습니다.
