### ISSUE TITLE
백준 코드 제출에서 코드 에디터 변경

### ISSUE THREAD

**Issue by smartwe** [joonas-yoon/boj-extended#141]
### 내용

```markdown
코드 에디터를 모나코로 바꾸는 기능도 좋을 것 같습니다!
```

**Comment by joonas-yoon** [comment]
에디터를 완전히 다른 라이브러리로 갈아끼우는 것은, 나중에 BOJ에서 에디터에 "멋진 기능"을 추가하면 동작이 엉망이 될 수 있습니다.

확장 프로그램의 범위 밖으로 보입니다.

**Comment by smartwe** [comment]
멋진 기능이 무엇을 의미하나요?

**Comment by joonas-yoon** [comment]
상상을 해보자면, 지금 BOJ에서 사용하고 있는 CodeMirror 에디터에 키워드 자동 완성 등의 기능이 추가될 때 문제가 생깁니다.

확장 프로그램에서 굳이 CodeMirror 를 모나코로 변경하면, 모나코로 위의 "자동 완성" 기능이 지원되도록 해야하기 때문이죠. 이건 PyCharm의 기능이 VS Code에서도 동작하도록 구현하는 것과 같아보입니다. (개발 난이도 아니라 역할과 범위의 문제라고 생각합니다.)

**Comment by joonas-yoon** [comment]
이슈는 닫도록 하겠습니다.
