### ISSUE TITLE
Rigel / Dark 모드에서 글자의 Background 강조가 들어간 부분의 가독성 문제

### ISSUE THREAD

**Issue by GyuHo123** [joonas-yoon/boj-extended#146]
### What happens

```markdown
Rigel / Dark 모드에서 문제의 입력 설명 중 글자의 Background 강조가 들어간 부분의 가독성이 매우 떨어지는 현상이 있습니다.
```

Dark Mode

![스크린샷 2023-03-09 233638](https://user-images.githubusercontent.com/74482513/224057640-bfc83fae-fdf6-47ce-8bf0-dcb896cdb90e.png)

Rigel Mode

![image](https://user-images.githubusercontent.com/74482513/224057942-8f1988cc-c8e6-4fd9-bd57-040d83d88b30.png)

### Operating System

Windows

### 환경

- OS: 10.0.22621.0
- Architecture: X64

### 확장 프로그램 버전

1.9.4

**Comment by joonas-yoon** [comment]
문제 링크가 어떻게 되나요?

**Comment by GyuHo123** [comment]
icpc.me/19583 입니다.

**Comment by joonas-yoon** [comment]
음.. 이 경우는 좀 난감하네요. 문제 원문이 아래와 같이 직접 배경색을 지정해서 작성된 경우라서, 제가 임의로 코드를 변경하기가 어려운 상황입니다

```
<code><span style="background-color:#dddddd;">HH:MM</span></code>
```

만약 이런 `background-color` 값을 직접 어두운 색으로 변경한다고하면, 실제로 문제 작성자가 "노란 배경색"을 의도했을 때 확장 프로그램이 문제 설명을 변경해버리는 불상사가 발생할 수 있습니다.

안타깝게도 현재로서는 해결 방법이 없어보이네요..

**Comment by GyuHo123** [comment]
확인했습니다! 감사합니다!
