### ISSUE TITLE
유저 티어 보여주기 오류

### ISSUE THREAD

**Issue by SycDevelop** [joonas-yoon/boj-extended#147]
### What happens

```markdown
모든 유저의 티어가 검은색 물음표 티어로 보입니다.
```

### Operating System

Windows

### 환경

 - OS: 10.0.19044.0
 - Architecture: X64

### 확장 프로그램 버전

1.9.4

**Comment by joonas-yoon** [comment]
https://github.com/joonas-yoon/boj-extended/issues/138
