### ISSUE TITLE
1.9.4.1 업데이트 이후에도 solved.ac 관련 기능이 작동하지 않음

### ISSUE THREAD

**Issue by motsuni04** [joonas-yoon/boj-extended#150]
### What happens
![image](https://i.imgur.com/8FJMwes.png)
![image2](https://i.imgur.com/pQnTLag.png)
#138에서 해당 이슈가 모두 해결되었다는 것을 확인하고, 확장 프로그램을 업데이트하고 solved.ac 사이트 엑세스 권한을 허용하였습니다만, 여전히 관련 기능이 작동하지 않음을 확인했습니다.  
혹시 추가로 설정이 필요한 부분이 있는 건가요?

![image3](https://i.imgur.com/mhyeK1e.png)
![image4](https://i.imgur.com/nLnoeXK.png)

### Operating System

Windows

### 환경

 - OS: 10.0.22000.0
 - Architecture: X64
 - Chrome 112.0.5615.138

### 확장 프로그램 버전

1.9.4.1

**Comment by motsuni04** [comment]
![img](https://i.imgur.com/Jz70512.png)
티어는 모든 유저가 아니라, 일부 유저만 보이지 않는 것 같습니다.

**Comment by tpwls6630** [comment]
![image](https://user-images.githubusercontent.com/3339760/233818658-e1b5bd84-87ac-450d-8a7b-94f1496a8e8e.png)

`
<a href="/problem/1012" class="result-ac problem-link-style-box" data-problem-id="1012" data-tier="0" data-problem-title="(가져오기 실패)">1012></a>
`

모든 문제에 대해 data-tier와 data-problem-title을 불러오지 못하고 있습니다.
user.js의 160:184에서 무슨 일이 일어나고있는거 같습니다...

**Comment by joonas-yoon** [comment]
안녕하세요, 정보를 가져오고 접근을 잘못하는 실수가 있었는데 알려주신 덕분에 수정했습니다. 감사합니다.

추가로 놓친 부분들도 https://github.com/joonas-yoon/boj-extended/pull/151 에서 함께 업데이트하였습니다.

일부 정보들은 캐싱되고 있어서, 24시간 이후에 갱신될 수 있으니 참고 부탁드립니다.
