### ISSUE TITLE
게시판 유저 티어 다크처리

### ISSUE THREAD

**Issue by C792** [joonas-yoon/boj-extended#153]
유저 티어를 보도록 설정했고 다크모드를 사용중일 때 게시판에서 댓글이나 글을 쓴 사람의 티어 이미지가 다크모드 처리되어 가독성이 떨어지는 것 같습니다.

![image](https://github.com/joonas-yoon/boj-extended/assets/89120533/0252e294-a3a7-4fa0-89ae-23ff4fa682f4)

티어 이미지는 ~/tier_small/n.svg 형태로 표현되니까 이 형태의 이미지들은 색상 반전 처리하지 않으면 좋겠네요.

![image](https://github.com/joonas-yoon/boj-extended/assets/89120533/768bdaba-8591-4c8e-908f-87002e7f5bcc)

**Comment by C792** [comment]
네네 딱히 OS나 브라우저 정보 혹은 사이트 주소와 무관하게 발생한다 판단하여 그런 정보들은 기재하지 않았습니다. 확인 감사합니다~

**Comment by motsuni04** [comment]
https://www.acmicpc.net/contest/view/965 처럼 대회 검수진, 대회 참가자 등의 티어도 다크 처리가 되어 보입니다. 확인 부탁드립니다!

**Comment by joonas-yoon** [comment]
확인 감사합니다. 아래와 같이 업데이트되었고, 다음 버전에 반영하도록 하겠습니다 :)

![image](https://github.com/joonas-yoon/boj-extended/assets/9527681/793903dd-523d-42ea-8cf6-b9a3ca321b33)
