### ISSUE TITLE
유저 페이지 문제 목록 정렬/필터링 기능

### ISSUE THREAD

**Issue by spotky1004** [joonas-yoon/boj-extended#154]
### 내용

'맞은 문제', '시도했지만 맞지 못한 문제', '맞은 번외 문제' 목록의 문제를 난이도순으로 정렬하거나 난이도 범위 또는 문제 제목으로 필터링할 수 있는 기능이 있으면 좋을 것 같습니다.

추가로 필터를 저장할 수 있게 만들어서 이전에 이미 필터 된 문제는 불러오지 않는다면, 불러올 문제 정보가 많은 유저 페이지에서 멈추는 현상을 줄일 수 있을 것으로 기대됩니다.

**Comment by joonas-yoon** [comment]
안녕하세요, 이렇게 아이디어를 제안해주셔서 감사합니다.

정리하자면 아래 두 가지 기능을 제안하신 것으로 이해됩니다.

1. 유저 페이지에서 문제를 난이도 순으로 정렬할 수 있는 기능 
2. 유저 페이지에서 문제 제목 검색/필터링 기능

말씀하신 기능은 하나씩 구현해보면서 여기에 업데이트 내용을 남기도록 하겠습니다 :)

그리고 중복으로 문제 정보를 불러오지 않는 방법은 이미 적용되어 있습니다 👍 감사합니다.

**Comment by joonas-yoon** [comment]
제안주신 정렬 기능에 대해서 고민해봤으나, 프로필 페이지는 최소한의 작업으로 CSS 렌더링 트리만 건드리는데도 페이지 로드에 성능 부하가 있는 상태입니다. 추가적인 기능을 넣기는 어려울 것 같고, 문제를 선별하고 정렬하는 방식에는 더 많은 기능을 지원하는 solved.ac 을 사용하시는 것을 권장드리겠습니다 😢 
이슈는 닫도록 하겠습니다.
