### ISSUE TITLE
올바르지 않은 위치에 유저 티어가 표시됨

### ISSUE THREAD

**Issue by motsuni04** [joonas-yoon/boj-extended#155]
### What happens
![image](https://i.imgur.com/1VLd0rj.png)
```
프로필 페이지에서 사진의 위치에 Unranked 티어 아이콘이 표시되는 문제가 있습니다.
```

### Operating System

Windows

### 확장 프로그램 버전

1.9.4.2

**Comment by joonas-yoon** [comment]
다음과 같이 해결되었습니다. 다음 업데이트에 반영하도록 하겠습니다. 감사합니다.

![image](https://github.com/joonas-yoon/boj-extended/assets/9527681/98813cd2-9539-4673-8ebd-994e6940f5d1)
