### ISSUE TITLE
백준 탭 여러개 켜놓고 프로필만 들어가면 크롬이 램때문에 죽어요

### ISSUE THREAD

**Issue by r4pidstart** [joonas-yoon/boj-extended#156]
### What happens

```markdown
백준 탭 열댓개 켜두고, 누군가의 프로필에 들어가면, 램 사용량이 치솟으면서 스왑메모리로 하드 공간까지 다 먹고 컴퓨터가 아예 다운됩니다.
평소에 풀 문제들 쌓아놓고 다니는 스타일인데 요즘 프로필만 들어가면 계속 죽다보니.. 크롬 작업관리자에서 살펴보니까 각각의 탭들이 다 메모리를 수 기가씩 먹더라고요.

그런데 이슈 글에 사진이 안 올라가요 선생님들
```

### Operating System

macOS

### 환경

 ~  sw_vers
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
 ~  uname
Darwin

### 확장 프로그램 버전

1.9.4.2

**Comment by r4pidstart** [comment]
<img width="676" alt="image" src="https://github.com/joonas-yoon/boj-extended/assets/67845112/50e4557c-8ae9-41a6-b81b-d1524c8acca8">

<img width="513" alt="image" src="https://github.com/joonas-yoon/boj-extended/assets/67845112/6c807d50-86f9-4da7-8c7d-f819e0b867b3">

<img width="1696" alt="image" src="https://github.com/joonas-yoon/boj-extended/assets/67845112/e8bdb6dc-e016-477a-b7db-370f9564d523">

<img width="579" alt="image" src="https://github.com/joonas-yoon/boj-extended/assets/67845112/97068fd8-1d79-4722-9379-d96649971a05">

**Comment by joonas-yoon** [comment]
혹시 확장 프로그램을 끄고 접속해도 동일하게 RAM 사용량이 치솓는 지 확인해주실 수 있을까요?

**Comment by r4pidstart** [comment]
방금 크롬 최신버전, 시크릿모드에서 해당 확장 활성화/비활성화 한 채로 동일하게 테스트해보니 확장 없을 때엔 탭별로 200mb정도의 메모리를 차지하는데, 확장 있으면 켜져있는 탭의 갯수가 많아짐에 따라 탭별로 2기가 이상도 차지하네요. 

이 상태에서 프로필 들어가니 컴퓨터가 죽었습니다.

**Comment by joonas-yoon** [comment]
그렇다면 탭마다 메모리를 차지하고 있다는 얘기가 되네요.. 음.. 자세히 파악해보고 어떻게 해결할 지 고민해보겠습니다. 감사합니다.

**Comment by spotky1004** [comment]
저도 이 문제를 겪었었는데 쿠키를 다 지웠더니 해결됐어요. 왜 해결 됐는지 정확한 이유는 모르겠어요.

**Comment by joonas-yoon** [comment]
아래 환경에서 장시간 사용해봤는데 증상이 재현되지 않아서 이슈는 종료하도록 하겠습니다.

- Apple M2 Pro
- macOS Sonoma 14.5
- Google Chrome 125.0.6422.142(공식 빌드) (arm64)
- BOJ Extened 1.9.5.1

이슈는 닫지만, 증상을 겪으시거나 해결하신 분들의 댓글 기다리고 있겠습니다. 감사합니다.
