### ISSUE TITLE
그룹 파일 하이퍼링크 관련

### ISSUE THREAD

**Issue by Annyeong-One** [joonas-yoon/boj-extended#159]
### What happens

```markdown
그룹 페이지에서 '파일' 버튼을 누르면 /group/files/(그룹 번호)로 이동하는데, 올바른 링크는 /group/file/(그룹 번호)입니다.
```

### Operating System

Windows

### 확장 프로그램 버전

1.9.4.2

**Comment by Annyeong-One** [comment]
![filebug](https://github.com/joonas-yoon/boj-extended/assets/79385636/fe27e068-d87e-485a-bd8d-a6e4aca4161b)

**Comment by joonas-yoon** [comment]
확인해보도록 하겠습니다. 감사합니다.

**Comment by joonas-yoon** [comment]
제보 감사합니다. 수정하였고 다음 버전에 반영하도록 하겠습니다. 감사합니다 :)
