### ISSUE TITLE
다크모드에서 설정 페이지의 solved.ac 로고가 잘 보이지 않음

### ISSUE THREAD

**Issue by star0202** [joonas-yoon/boj-extended#160]
### What happens

```markdown
다크모드에선 설정 페이지의 `문제 난이도`와 `유저 티어` 옵션 밑에 있는 solved.ac 로고가 잘 보이지 않음
```

### Operating System

Windows

### 환경

 - OS: 10.0.19045.0
 - Architecture: X64

### 확장 프로그램 버전

v1.9.4.2

**Comment by star0202** [comment]
![image](https://github.com/joonas-yoon/boj-extended/assets/61998307/825ac6ee-c504-48ef-833a-635424842176)

**Comment by joonas-yoon** [comment]
음 이거는 제 쪽에서는 해결하기 어려워보이는데, solved 글자가 흰색으로 적혀있는 배경 투명한 이미지가 있을까요?

**Comment by joonas-yoon** [comment]
와우 PR까지 같이 올려주셨군요 정말 감사합니다.

리뷰 후 반영하도록 하겠습니다 :)
