### ISSUE TITLE
30000 이상 문제 제목표시 오류

### ISSUE THREAD

**Issue by erickk1212** [joonas-yoon/boj-extended#165]
### What happens

```markdown
번호 30000 이상인 문제 제목이 유저 페이지, 유저 비교에서 (가져오기 실패)로 뜹니다.
```

### Operating System

Windows 11

### 환경

 " - OS: $([Environment]::OSVersion.Version)"
 OS: 10.0.22621.0
" - Architecture: $((Get-AppxPackage -Name Microsoft.WindowsCalculator).Architecture)"
 Architecture: X64

### 확장 프로그램 버전

1.9.5

**Comment by joonas-yoon** [comment]
여러 차례 확인해봤는데, 시간이 조금 지나니 정상적으로 표시되었습니다.

![image](https://github.com/joonas-yoon/boj-extended/assets/9527681/eaabd7f5-72a8-4b3e-8acf-45f4d1c05bf0)

서버에 무리한 요청을 방지하기 위한 캐싱 처리때문에 업데이트에 시간이 조금 소요될 수 있습니다. 참고 부탁드립니다.

이슈는 닫겠습니다. 리포트 감사합니다 :)
