### ISSUE TITLE
문제 티어 표시

### ISSUE THREAD

**Issue by lukeacd08** [joonas-yoon/boj-extended#167]
### 내용

```markdown
문제 난이도를 표시할 때 나오는 작은 마커가 문제의 중간에 올 수 있게 해주세요. margin-top: 5px 정도 하면 맞는것 같습니다
```

**Comment by joonas-yoon** [comment]
문제 페이지에서 표시되는 이미지를 말씀하시는건가요?

티어가 여러 곳에서 표시되고 있어서 어디를 가리키시는지 스크린샷이 있으면 좋겠습니다.

**Comment by dlgudw123** [comment]
스크린샷 첨부하겠습니다

![{F06D7519-C0E3-4CD5-A91F-304FD7F5FC6E}](https://github.com/user-attachments/assets/38f332d6-aa19-44f3-a9ba-177d5be9a75c)

아이콘이 세로 정렬 가운대로 왔으면 좋겠습니다

**Comment by joonas-yoon** [comment]
아하 이 부분이었군요..

여기는 처음에 세로 가운데 정렬로 해보았었는데요.
휘장 모양이 윗면은 평평하고 아래는 뾰족해서 공중에 붕 떠있는 느낌이라 어색했습니다.

그래서 휘장이 박스에 걸려있듯이 위쪽 기준으로 붙어있도록 의도한거라 디자인 변경은 어렵겠네요.

이슈 리포트에 스크린샷까지 첨부해주셔서 감사합니다.
이슈는 닫도록 하겠습니다.

**Comment by joonas-yoon** [comment]
가 아니라 작성자분과 다른 분이군요?

스크린샷을 요청드렸던 이유는 아래 2가지 케이스를 확인하고 싶어서였습니다.

1. 위와 같은 프로필 페이지의 문제 표시
2. 문제 목록에서 테이불 내 표시되는 마커 (테이블 셀의 중앙에 오게 해달라는 건지?)

**Comment by dlgudw123** [comment]
작성자님이 margin-top: 5px;을 언급하셔서 보기에 약간 위로 치우쳐진 느낌을 말하려는 의도인 것 같아 대신 스크린샷을 첨부해 보았습니다.

휘장이 걸려있기 때문에 위에 정렬된다는 것은 듣고 보니 맞는 말 같습니다. 그런데 혹시 휘장 크기를 키워서 완전히 중앙은 아니지만 높이가 비슷하도록 만드는 것에 대해서는 어떻게 생각하시나요?

**Comment by joonas-yoon** [comment]
가로/세로 길이와 함께 숫자 크기가 같이 커져서, 난이도의 숫자와 문제 번호/제목과의 폰트 크기가 다른 문제가 생깁니다 :/

**Comment by joonas-yoon** [comment]
해당 이슈는 닫도록 하겠습니다. 감사합니다.
