### ISSUE TITLE
스코어보드 폰트 색상

### ISSUE THREAD

**Issue by ddjddd** [joonas-yoon/boj-extended#17]
👋 안녕하세요! ✨새로운 기능 요청✨에 무척 반가운 마음입니다.

# 내용

![image](https://user-images.githubusercontent.com/26399087/121988911-27d68e00-cdd6-11eb-8c76-f00a488f410f.png)
글자가 하나도 안보입니다

**Comment by joonas-yoon** [comment]
리포트 감사합니다. 수정하였습니다.

![image](https://user-images.githubusercontent.com/9527681/124287962-957f0a00-db8b-11eb-9e11-15de40f12a55.png)
