### ISSUE TITLE
제보입니다.

### ISSUE THREAD

**Issue by pokmui** [joonas-yoon/boj-extended#18]
👋 안녕하세요, 제보해주셔서 감사합니다!

## 내용
https://www.acmicpc.net/status 에서 계속 흔들립니다.

## 환경
Chrome

**Comment by joonas-yoon** [comment]
제보 감사합니다 👋

흔들린다는 게 칸의 너비가 들쭉날쭉 바뀐다는 의미시죠?

지금 코드는 "문제", "결과" 이렇게 2개는 너비가 가변적이도록 설정했습니다.

'문제 제목 보기' 상태에서 문제 제목이 긴 경우가 많아서 그렇게 했는데, 너비가 흔들리는 케이스는 어떻게 처리를 하는 게 좋을 지 모르겠네요.

제 컴퓨터에서 테스트로 너비를 고정해보고 사용하면서 증상을 살펴보겠습니다.

감사합니다.

**Comment by joonas-yoon** [comment]
여러 개가 동시에 채점될 때, 텍스트 길이가 서로 다르면 떨리는 현상을 확인했습니다.

길이를 고정시켜서 수정했고, `v1.5.2` 버전에 적용되었습니다 :)

**Comment by pokmui** [comment]
채점 현황 - Chrome 2021-08-03 18-03-49.mp4
<https://drive.google.com/file/d/1tvOjneqgJrfE1Rrx-EBL8rI7-m1g-ODZ/view?usp=drive_web>
흔들림 현상이 또 발견되었습니다.

2021년 7월 26일 (월) 오후 9:44, Joona Yoon ***@***.***>님이 작성:

**Comment by joonas-yoon** [comment]
아... 이런 현상이었군요. 이슈를 다시 열겠습니다

Get Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by joonas-yoon** [comment]
1.5.3 버전에서 수정하였습니다. 리포트 감사합니다.
