### ISSUE TITLE
결과 커스터마이징

### ISSUE THREAD

**Issue by voiciphil** [joonas-yoon/boj-extended#2]

**Comment by joonas-yoon** [comment]
https://github.com/justiceHui/Hell-BOJ-Verdict-Message

이거 말하시는거?

**Comment by voiciphil** [comment]
맞았습니다!!

**Comment by joonas-yoon** [comment]
https://github.com/joonas-yoon/boj-extended/commit/0b8636358c385a5ca321111c62c62609d61329d9#diff-431e5adb210d9982cdf7bacdacad1bab1cd70c57028cb41316d8bb79d2d8b046R17
