### ISSUE TITLE
제출 언어 chosen container back color 와 fore color 시인성 개선

### ISSUE THREAD

**Issue by Kuass** [joonas-yoon/boj-extended#26]
## 내용
제출의 언어 행 chosen-container 의 시인성이 좋지 않음

## 환경
- Windows 10 `Build 19041.1165`
- Chrome `v92.0.4515.159`

## 오류 메시지 또는 스크린샷
![image](https://user-images.githubusercontent.com/5186106/131216954-a1154c86-a8c6-44b0-97e1-56c6f9908487.png)

**Comment by joonas-yoon** [comment]
제보 감사합니다. 다음 버전에서 아래처럼 적용될 예정입니다 :)

![image](https://user-images.githubusercontent.com/9527681/131237431-cd38328f-c16e-4cf1-8162-32eab2749fa5.png)
