### ISSUE TITLE
기본 크기 옵션 선택시 여백이 없어집니다.

### ISSUE THREAD

**Issue by tuna1210** [joonas-yoon/boj-extended#31]
## 내용

기본 크기 옵션일 때 창 너비를 좁게 만들면 양쪽 여백이 없습니다. 근데 넓게 보기 옵션일 때는 정상적으로 여백이 있습니다.

## 환경

Chrome 93.0.4577.82 (arm64)  

## 오류 메시지 또는 스크린샷

* 기본 크기
![image](https://user-images.githubusercontent.com/34531488/133211799-77f148e0-f3e1-4992-b374-c5803d5366eb.png)
* 넓은 크기일 때 ( or 확장프로그램 비활성화 시)
![image](https://user-images.githubusercontent.com/34531488/133212231-ec2e0ecd-6444-46e3-aca3-aa0002c9bc48.png)

**Comment by joonas-yoon** [comment]
해당 내용은 [1.5.8 버전](https://github.com/joonas-yoon/boj-extended/releases/tag/v1.5.8)에 적용되었습니다. 감사합니다.
