### ISSUE TITLE
도움말에 테마 적용

### ISSUE THREAD

**Issue by Yukariko** [joonas-yoon/boj-extended#33]
![image](https://user-images.githubusercontent.com/3056753/133734100-2ec03cc8-242d-4d33-98e2-29a7379ac621.png)

다크모드 사용시 도움말에도 다크모드가 지원되었으면 좋겠습니다.
문제 타이머에도 다크모드가 풀리네요

**Comment by joonas-yoon** [comment]
문제 타이머는 완전히 몰랐네요. 빠르면 다음 주에 바로 수정 후 적용하겠습니다.

여담으로, 테마 추천 받습니다.

**Comment by Yukariko** [comment]
제 개인적으로는 현재 다크 테마가 꽤 마음에 듭니다. 
다만 아래같이 채점현황을 보았을 때, 대비가 좀 높다는 인상을 받아서 대비가 낮은 버전도 괜찮겠네요

![image](https://user-images.githubusercontent.com/3056753/133755794-f90428fe-c59a-4388-a481-a2df2aa1d4a0.png)

**Comment by joonas-yoon** [comment]
해당 내용은 [1.5.8 버전](https://github.com/joonas-yoon/boj-extended/releases/tag/v1.5.8)에 적용되었습니다. 감사합니다.
