### ISSUE TITLE
채점 텍스트 변경 하이퍼링크 및 total number 기능 지원

### ISSUE THREAD

**Issue by mym0404** [joonas-yoon/boj-extended#35]
# 내용

![image](https://user-images.githubusercontent.com/33388801/134729951-6fd3d1bb-76ef-4f7b-b5c5-2f3ad0928194.png)
- subtask가 있는 문제거나 컴파일 에러가 난 경우 hyperlink 가 적용되며 눌러서 subtask 결과 및 컴파일 에러 이유를 볼 수 있는데,  텍스트를 변경하면 하이퍼링크가 활성화되지 않는듯 합니다.

- `:number:` 로 숫자 placeholder 가 적용되어있는데 subtask 같은 경우 12/100 과 같이 전체 개수까지 표시가 되어야 하는데 이 부분은 어떻게 설정하는건지 잘 모르겠습니다.

잘 쓰고 있습니다 개발 감사드립니다.

**Comment by joonas-yoon** [comment]
제보 감사합니다.

스크린샷에 있는 제출의 제출 번호가 어떻게 되나요?
그걸로 테스트를 해보겠습니다.

**Comment by mym0404** [comment]
![image](https://user-images.githubusercontent.com/33388801/134762385-966db4c5-d104-41c5-adaa-8b29bc7bce7f.png)
제출 번호 `33703677` 입니다.

그리고 현재는 다음과 같이 설정하여 사용합니다.
![image](https://user-images.githubusercontent.com/33388801/134762398-66646b7f-b3af-4d89-9f85-489128a2989f.png)

부분 점수는 제대로 total을 표기해주지않기에 변형해서 사용하지 않는 상태입니다.
@joonas-yoon

**Comment by joonas-yoon** [comment]
["전체 채점" 유형의 문제들](https://www.acmicpc.net/problemset?sort=no_asc&style=full&style_if=and)이 문제였군요..

전부터 :number: 만으로는 억지스럽게 변환하고 있어서 바꾸고 싶었는데, 예외가 생각보다 많아서 정리를 좀 하고 바꿔볼게요.

제가 알기로는 숫자가 등장하는 케이스들은 이렇습니다 (텍스트 - 결과 타입) :

- `맞았습니다!!` - AC
- `맞았습니다!! (00/00)` - AC  [(참고)](https://www.acmicpc.net/status?radio-extended=on&problem_id=20166&user_id=&language_id=-1&result_id=4&from_problem=1)
- `맞았습니다!! (00점)` - AC [(참고)](https://www.acmicpc.net/status?radio-extended=on&problem_id=10946&user_id=&language_id=-1&result_id=4&from_problem=1)
- `00점` - PAC [(참고)](https://www.acmicpc.net/status?radio-extended=on&problem_id=3090&user_id=&language_id=-1&result_id=4&from_problem=1)
- `채점중 (00%)` - JUDGING
- `틀렸습니다 [4]` - WA [(참고)](https://www.acmicpc.net/status?radio-extended=on&problem_id=17690&user_id=&language_id=-1&result_id=6&from_problem=1)

덕분에 케이스를 하나 더 찾았습니다. 감사합니다.

**Comment by joonas-yoon** [comment]
하이퍼링크가 사라지던 버그는 수정하였고, [`1.5.8` 버전](https://github.com/joonas-yoon/boj-extended/commit/6412d52a01273a2a7eb1d054edc740ba9ce80904)에 적용하였습니다!

**Comment by mym0404** [comment]
수정 감사합니다. 숫자 포맷 버그 부분은 따로 이슈를 만들도록 하겠습니다!

**Comment by sion-k** [comment]
사소한 이슈지만, 제출 후에 런타임 에러가 발생하는 경우 런타임 에러의 원인을 찾는 중 (00%)이렇게 퍼센트가 올라가는데 이렇게 되면 무조건 100%까지 진행되었다가 틀린 것 처럼 보입니다.
![image](https://user-images.githubusercontent.com/44183313/152673286-d382a66c-590f-45fc-b1a6-78331e51a59a.png)

**Comment by joonas-yoon** [comment]
@sion-k 실제로는 2%에서 틀렸는데 100% 로 바뀐건가요?

**Comment by sion-k** [comment]
네, 런타임 에러를 찾는데도 시간이 걸려서 퍼센트가 올라가는데 그거를 어디까지 채점되었는지로 판단하는 것 같습니다
