### ISSUE TITLE
재채점 화면에서 재채점 결과가 두번씩 출력됨

### ISSUE THREAD

**Issue by tuna1210** [joonas-yoon/boj-extended#36]
## 내용

재채점 결과 화면에서 바뀐 결과 부분이 두번씩 출력됩니다.
런타임에러만 정상적으로 출력되네요

## 환경

Chrome 93.0.4577.82(공식 빌드) (arm64)

## 오류 메시지 또는 스크린샷

<img width="1200" alt="스크린샷 2021-09-25 오후 5 07 40" src="https://user-images.githubusercontent.com/34531488/134764318-63717731-96c0-4554-9436-4c35da9da62c.png">

**Comment by joonas-yoon** [comment]
아.. 이건 난감하네요.

- 채점 현황: `<span class="result-text result-ac" data-color="ac">맞았습니다!!</span>`
- 소스 보기 (공유 포함): `<span class="result-ac" data-color="ac">맞았습니다!!</span>`
- 재채점 결과: `<span class="result-ac">맞았습니다!!</span>`, `<span class="result-text"><span class="result-ac">맞았습니다!!</span></span>`

몇 주 전에 바뀌고는 클래스 이름의 패턴이 일정하지 않은데, 일단 수정해보겠습니다.

**Comment by joonas-yoon** [comment]
해당 내용은 [1.5.9 버전](https://github.com/joonas-yoon/boj-extended/releases/tag/v1.5.9)에 적용되었습니다. 감사합니다.
