### ISSUE TITLE
:number: 포맷 버그(부분 점수)

### ISSUE THREAD

**Issue by mym0404** [joonas-yoon/boj-extended#37]
# 내용

![image](https://user-images.githubusercontent.com/33388801/134729951-6fd3d1bb-76ef-4f7b-b5c5-2f3ad0928194.png)

- `:number:` 로 숫자 placeholder 가 적용되어있는데 subtask 같은 경우 12/100 과 같이 전체 개수까지 표시가 되어야 하는데 이 부분은 어떻게 설정하는건지 잘 모르겠습니다.

![image](https://user-images.githubusercontent.com/33388801/134762385-966db4c5-d104-41c5-adaa-8b29bc7bce7f.png)

설정을 해제하면 다음과 같이 subtask문제 잘 표시가 됩니다.
![image](https://user-images.githubusercontent.com/33388801/134762461-b466ae8c-9609-42f3-ad49-374800b623f5.png)

그리고 현재는 다음과 같이 설정하여 사용합니다.
![image](https://user-images.githubusercontent.com/33388801/134762398-66646b7f-b3af-4d89-9f85-489128a2989f.png)

감사합니다.

해당 이슈는 #35 에서 따로 분리되어 올려졌습니다.

**Comment by joonas-yoon** [comment]
케이스가 생각보다 많고 깔끔하게 텍스트를 대치시키기가 어려워보여서 우선 제거했습니다 ㅠㅠ

더 좋은 형태로 제공할 수 있을 때, reopen 하도록 하겠습니다.

[1.5.9 버전](https://github.com/joonas-yoon/boj-extended/releases/tag/v1.5.9)에서는 숫자 포맷을 삭제하여 배포하였습니다. 감사합니다.
