### ISSUE TITLE
제출 코드 작성란 버그 

### ISSUE THREAD

**Issue by Betacores** [joonas-yoon/boj-extended#38]
![image](https://user-images.githubusercontent.com/48412380/135722484-8c77f791-0033-43e0-bf62-c511b107e917.png)

백준 설정에서 선택한 Lucario 테마 사용 + boj extend 다크모드 사용하면 
제출란이나 코드 보기란에서 코드의 라인이 매겨지는곳과, 테두리가 저렇게 하늘색으로 붕 뜹니다.
결국 코드의 라인 넘버도 안보입니다.

**Comment by joonas-yoon** [comment]
안녕하세요. 제보 감사합니다 :)

해당 이슈는 아래에서 수정되었고, 1.5.9 버전에서 적용될 예정입니다!

https://github.com/joonas-yoon/boj-extended/issues/34#issuecomment-930172543

**Comment by joonas-yoon** [comment]
Lucario 테마 사용 + boj extend 다크모드 조합으로 확인한 스크린샷입니다.

![image](https://user-images.githubusercontent.com/9527681/135742049-4ef88d4a-8c77-4faa-a7c3-82b04a6ca457.png)

**Comment by joonas-yoon** [comment]
해당 내용은 [1.5.9 버전](https://github.com/joonas-yoon/boj-extended/releases/tag/v1.5.9)에 적용되었습니다. 감사합니다.
