### ISSUE TITLE
대회>외부 화면에 다크모드적용

### ISSUE THREAD

**Issue by comment2** [joonas-yoon/boj-extended#46]
## 내용

https://www.acmicpc.net/contest/other/list 에 다크모드가 이상하게 적용되었습니다.

## 환경

window 10, 크롬브라우저
## 오류 메시지 또는 스크린샷

![image](https://user-images.githubusercontent.com/86146642/139787572-a934922c-26d8-41e4-bb45-e2aa3752b01c.png)

**Comment by comment2** [comment]
간단한 버그같아서
```theme-dark.css```에 
```
html[theme='dark'] .table-bordered > tbody > tr.striped > td {
  background-color: #1f1f1f;
}
```
를 추가하여 고쳤습니다.
![image](https://user-images.githubusercontent.com/86146642/139788933-c27009cb-c3b6-441e-b092-4bdfb47558be.png)


contribute하기전에 궁금한게 있습니다.
readme.md에는 npm run build를 이용하여 빌드하는 것같던데 이게 잘 안되어서 local에 다운받은 boj-extend의 코드를 수정하고 "chrome://extensions/" > "개발자모드" > "압축해제된 확장 프로그램 로드" 를 이용해 확인하는 방식으로 개발하였는데 이 방식으로해도 괜찮을까요?

**Comment by joonas-yoon** [comment]
@comment2 

네, 그렇게 확인하신 것이 정확히 맞습니다! 저도 그 방식으로 개발하고 있구요.

`num run build` 는 git bash 환경에서만 동작할 것입니다. `CMD` 나 `PowerShell` 에서는 확인하지 못했습니다. 

build 과정은 웹 스토어에 올려서 배포하기 전에, 코드 압축 + 최적화 등을 수행하고 스토어에 그대로 올려도 되는 지 동작을 확인하는 단계라 개발하실 때는 생략하셔도 됩니다.

https://github.com/comment2/boj-extended/commit/6c19c50888eadd95c667ae8cffd4fd2227f5730d 은 PR로 올려주시면 다음 업데이트에 반영하도록 하겠습니다. 🎉 

감사합니다 😄
