### ISSUE TITLE
Firefox addon 업데이트를 부탁드립니다.

### ISSUE THREAD

**Issue by Jhyub** [joonas-yoon/boj-extended#52]
https://addons.mozilla.org/ko/firefox/addon/boj-extended/
Firefox의 boj-extended는 아직 1.5.3에 머물러 있습니다.
해당 저장소의 애드온 업데이트를 부탁드리겠습니다.
또한, 해당 프로젝트를 xpi 파일로 컴파일 하는 방법도 알려주시면 감사하겠습니다.

**Comment by joonas-yoon** [comment]
[comment at #9](https://github.com/joonas-yoon/boj-extended/issues/9#issuecomment-964655286) 이슈에 있기는 한데,

제가 1.5.3 버전을 올리고, 다시 들어가려니까 제 계정이 막혀있는 상태입니다 ;;

앱을 설치해서 2-factor-auth 인증을 하라는데, 해결되면 배포하고 여기에 업데이트 공유하겠습니다.

위 댓글을 적을 당시에 xpi 파일로 컴파일해서 `.crx`, `.dmg` 파일처럼 올려보려고 했는데, `.xpi` 은 왜인지 깨지더라구요.
아무래도 manifest.json 스펙 호환성 때문 같은데, 그럼 1.5.3 버전은 도대체 어떻게 올라갔는 지 저도 의문입니다..

**Comment by joonas-yoon** [comment]
제가 참고했던 링크들입니다. 도움이 되면 좋겠습니다.
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities
- https://blog.chosunghyun.com/porting-a-chrome-extension-to-firefox-add-on/

**Comment by joonas-yoon** [comment]
@Jhyub 계정을 찾았고 오류 수정해서 가장 최신 버전인 1.6.1을 배포했습니다! https://addons.mozilla.org/ko/firefox/addon/boj-extended/versions/

FireFox는 검토 없이 바로 배포되네요.

관심 가져주셔서 감사합니다 :)

**Comment by Jhyub** [comment]
감사합니다!! :smile: :+1:
