### ISSUE TITLE
문제 검색 시 해결한 문제인지 표시하는 기능

### ISSUE THREAD

**Issue by pressogh** [joonas-yoon/boj-extended#54]
**내용**

백준에서 문제 검색을 할 시 이 문제를 풀었는지 안풀었는지 확인할 수 있는 기능
문제 이름 옆에 [해결함] 등이 표시되는 기능이 있으면 좋을 것 같습니다.
[https://www.acmicpc.net/search#q=&c=Problems](https://www.acmicpc.net/search#q=&c=Problems)

백준에서 문제 검색을 했을 때, 이 문제가 내가 푼 문제인지 아직 안푼 문제인지 긴가민가하여 문제에 들어가서 확인해보는 일이 많아 이 기능의 필요성을 느꼈습니다.

**Comment by joonas-yoon** [comment]
오 감사합니다. 좋은 아이디어네요!

최근에 시간이 좀 없는데, 검색 페이지와 빠른 검색에서 모두 되도록 구현해볼게요. 업데이트 되면 댓글 달겠습니다.

**Comment by joonas-yoon** [comment]
구현 완료되었으며, 다음 업데이트에 추가될 예정입니다.

## 검색 페이지 > 문제 탭
![image](https://user-images.githubusercontent.com/9527681/148529321-93a06d20-7145-4a3c-97fb-999c8b4d0db7.png)

## 검색 페이지 > 게시판 탭
![image](https://user-images.githubusercontent.com/9527681/148529462-228efec3-4949-4e46-b70c-bb6039abad39.png)

**Comment by joonas-yoon** [comment]
[1.7.0 버전](https://github.com/joonas-yoon/boj-extended/pull/57)에 추가되었습니다.

곧 Chrome/FireFox/Whale 스토어에 배포될 예정입니다. 감사합니다.
