### ISSUE TITLE
정답 여부에 따라 맞은 문제의 제목과 함께 강의, 로그아웃 버튼도 색이 바뀜

### ISSUE THREAD

**Issue by Kredsya** [joonas-yoon/boj-extended#64]
**내용**

맞으면 초록색, 틀리면 빨간색으로 강의, 강의 요청하기, 로그아웃의 색이 바뀜.
문제 화면에서만 이렇게 보이고 다른 탭에서는 그렇지 않음.
![image](https://user-images.githubusercontent.com/47083922/150113937-54a19188-91d2-4c81-9d53-5860f82d39f8.png)
![image](https://user-images.githubusercontent.com/47083922/150113973-c92ecfe2-ec07-4f8e-8675-fdffce05a2d4.png)
![image](https://user-images.githubusercontent.com/47083922/150114048-0db7e022-9525-4aa4-bff5-a9a34d62a39a.png)

**환경**
 - Browser: Chrome/97.0.4692.71
- OS: Windows Major 10 Minor 0 Build 19043 Revision 0
- Architecture: X64

**Comment by joonas-yoon** [comment]
엇 그렇네요.. 버그 제보 정말 감사합니다!!

메모 작성하기 버튼까지 색깔이 바뀌는군요. 금방 고칠 수 있을 것 같네요.

**Comment by joonas-yoon** [comment]
1.7.3 버전에 반영하였고, 크롬 스토어부터 배포하였습니다. 감사합니다 (●'◡'●)
