### ISSUE TITLE
문제 탭에서 맞힌 문제의 경우 강의와 로그아웃 글씨가 초록색으로 나옵니다 

### ISSUE THREAD

**Issue by sion-k** [joonas-yoon/boj-extended#66]
**내용**

result-ac라는 class가 적용되어서 그런 것 같습니다

![image](https://user-images.githubusercontent.com/44183313/150269893-e555c37d-8a63-4237-9356-4000e03b270f.png)

**환경**

 - Browser: Chrome
 - OS: Win10
 - Architecture:

![image](https://user-images.githubusercontent.com/44183313/150269769-79f15d1c-1928-4d30-a473-eab455d76680.png)

**Comment by joonas-yoon** [comment]
해당 버그는 수정하였고 어제 업로드하긴 했는데, 배포까지 시간이 좀 걸리는 듯 합니다!

조금만 기다려주세요, 제보 감사합니다!! 😊

Duplicate issue of #64

**Comment by joonas-yoon** [comment]
배포 되었습니다.
