### ISSUE TITLE
문제 페이지 질문 검색 탭 괄호 안의 게시글 개수가 0으로 고정되어 표시됩니다.

### ISSUE THREAD

**Issue by uSafeSpot** [joonas-yoon/boj-extended#67]
**내용**

질문 검색 탭 괄호 안의 게시글 개수가 0으로 고정되어 표시됩니다. 
아래는 1000번 문제 페이지 일부입니다.

![image](https://user-images.githubusercontent.com/93824976/150273345-15e23248-587e-4236-8067-930db4c46c95.png)
**환경**

 - Browser: Chrome 97.0.4692.71
 - OS: Windows 10.0.19043.0 (21H1)
 - Architecture: x64

**Comment by joonas-yoon** [comment]
어... 생각보다 어렵네요. 시간이 좀 걸릴 것 같습니다.

전부터 다른 이유로 문제를 가지고 있다고 생각하는 기능이었는데, 잠시 사라질 수도 있겠습니다.

**Comment by joonas-yoon** [comment]
우선 현재 파악하기로는, 질문 게시판을 확인했지만 공지글밖에 없는 (??) 상태로 긁어오고 있네요.

브라우저에서 해당 기능을 직접 동작시켜보면, 공지글+질문글이 모두 로드되어있는데,
확장 프로그램에서 실행하면 (조금 더 앞선 타이밍으로 예상), 공지글만 로드된 채로 읽어오고 있습니다 ;;

관측하기 전까지는 질문글이 없었는데... 관측하면 있습니다...

여러 실험을 해보고 업데이트가 되면 여기에 코멘트로 다시 공유드리겠습니다 😢

**Comment by joonas-yoon** [comment]
유틸 함수를 수정하면서 생긴 문제였네요. 쉽게 해결했습니다.

> 전부터 _다른 이유로 문제를 가지고 있다고_ 생각하는 기능이었는데, 잠시 사라질 수도 있겠습니다.

위의 문제도 함께 해결하였습니다.

다음 업데이트(`1.7.4`)에 반영하도록 하겠습니다.

**Comment by joonas-yoon** [comment]
1.7.5버전에 포함되었으며, 크롬 웹스토어에 업로드하였습니다. 배포까지는 시간이 조금 걸릴 수 있습니다 :)

**Comment by tuna1210** [comment]
1.7.5.2 버전인데 여전히 0으로 보입니다.
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/34531488/156194146-17103edc-3362-4324-8774-a22fe8551a1e.png">
<img width="356" alt="image" src="https://user-images.githubusercontent.com/34531488/156194419-730824eb-d7b4-4e7f-a425-d12c9f7b5248.png">

**Comment by joonas-yoon** [comment]
> 1.7.5.2 버전인데 여전히 0으로 보입니다. 

@tuna1210 이 이슈를 포함해서 알림페이지에서 문제 해결 여부를 표시하는 것도 함께 안되고 있는데,

프로필 페이지를 조회할 때 아무 응답도 받지 못하고 있는 게 원인으로 보입니다. (`responseText`가 비어있음)

만약 사이트에서 페이지 요청 헤더를 보고 막았다면, 다른 방법을 생각해봐야해서 시간이 많이 걸릴 듯 합니다.
