### ISSUE TITLE
cph 테스트케이스 자동 등록

### ISSUE THREAD

**Issue by manguuu** [joonas-yoon/boj-extended#68]
**내용**
https://github.com/jmerle/competitive-companion
위의 확장프로그램의 기능과 같이 vscode 플러그인인 cph에 테스트케이스가 자동으로 등록되는 기능이 추가되면 좋을 것 같습니다.

**Comment by manguuu** [comment]
리드미 지원 항목에 BOJ가 없길래 지원 여부를 몰랐습니다.
덕분에 저도 알아가네요. 감사합니다.

**Comment by joonas-yoon** [comment]
저도 감사합니다 :) 이슈는 닫을게요 그럼!
