### ISSUE TITLE
문제 재접속 시 질문검색 개수가 안보이는 버그

### ISSUE THREAD

**Issue by Kredsya** [joonas-yoon/boj-extended#72]
**내용**

새로고침, 다른 탭 갔다 돌아오기 등등 새로 페이지를 불러오면 질문검색 옆 개수가 사라지는 버그가 있습니다.

![1](https://user-images.githubusercontent.com/47083922/151546586-e43c9684-dc0b-4c90-951f-f3abd5bc2b9f.png)
![2](https://user-images.githubusercontent.com/47083922/151546611-ab656cf8-fa6c-4591-81e9-99ed75955666.png)

**환경**

Browser: Chrome/97.0.4692.71
OS: Windows Major 10 Minor 0 Build 19043 Revision 0
Architecture: X64

**Comment by Kredsya** [comment]
쿠키 삭제나 컴퓨터 재부팅은 아직 안해봤습니다.

**Comment by joonas-yoon** [comment]
버그 리포트 감사합니다. 저도 몇차례 시도해보고 현상 확인해보고 여기에 내용 확인 + 버그 수정 기록을 업데이트해보겠습니다

**Comment by joonas-yoon** [comment]
문제가 생길만한 곳을 고치긴 했는데, 어떤 경로로 발생한 버그인지를 몰라서 정확히 확인은 못했습니다.

[`dev`](https://github.com/joonas-yoon/boj-extended/tree/dev) 브랜치를 다운받으셔서 크롬에 설치하시면 확인하실 수 있습니다. [설치 방법](https://github.com/joonas-yoon/boj-extended/#%EC%84%A4%EC%B9%98-%EB%B0%8F-%EC%82%AC%EC%9A%A9)
