### ISSUE TITLE
부분점수에서의 퍼센트 기록

### ISSUE THREAD

**Issue by conmover** [joonas-yoon/boj-extended#74]
안녕하세요 boj extended를 고맙게 사용중인 백준 유저입니다.
퍼센트 기록 옵션을 유용하게 사용하고 있는데 부분점수 문제에서도 적용됐으면 해서 기능 요청드립니다.
**내용**

부분점수를 맞을때도 퍼센트가 떴으면 좋겠습니다

부분점수 문제에 대해 코드A가 코드B보다 얼마나 더 많은 테스트케이스가 통과될까를 확인하기 위해 필요합니다.

**Comment by joonas-yoon** [comment]
이전에 정리했던 케이스들이 있는데 참고해서 반영해보겠습니다.

https://github.com/joonas-yoon/boj-extended/issues/35#issuecomment-927043028

감사합니다!

**Comment by joonas-yoon** [comment]
정말 오래 기다리셨습니다. 이슈 해결하였고, 다음 업데이트에 반영될 예정입니다 :)

![image](https://user-images.githubusercontent.com/9527681/185736731-6abd17a7-4a36-4e80-b8ac-75b615778ae6.png)

**Comment by joonas-yoon** [comment]
[1.8.4 버전](https://github.com/joonas-yoon/boj-extended/pull/108)에 추가되었습니다 🎉
