### ISSUE TITLE
모비일에도 적용이 가능한 건가요?

### ISSUE THREAD

**Issue by JipDol2** [joonas-yoon/boj-extended#75]
모바일에서도 이 기능을 사용하고 싶습니다.
혹시 가능 할까요??

**Comment by joonas-yoon** [comment]
FireFox 모바일에서도 사용가능하게 배포하긴 했는데 테스트해보지는 못했어요.

저는 모바일에서는 Yandex 라는 앱으로 확인해보고 있어요.
