### ISSUE TITLE
SETTING

### ISSUE THREAD

**Issue by smartwe** [joonas-yoon/boj-extended#76]
설정에서 BOJ EXTENDED 설정이 openSettingPage
으로되있던데 혹시 이부분을 다른 코드로 대체할 수 있다면 어떤 코드로 대체할 수 있나요?

**Comment by smartwe** [comment]
setting.js 요

**Comment by smartwe** [comment]
(https://www.acmicpc.net/modify)

**Comment by joonas-yoon** [comment]
https://github.com/joonas-yoon/boj-extended/blob/21a922f7292d3efed1eb06d0e1e34d214654b92a/js/setting.js#L8

여기를 말씀하신거였군요? 이 부분은 background 에 제가 임의로 전달한 거라서 아무거나 될 수 있어요.

https://github.com/joonas-yoon/boj-extended/blob/21a922f7292d3efed1eb06d0e1e34d214654b92a/js/background.js#L117-L121

여기를 참고하시면 됩니다

**Comment by smartwe** [comment]
근데 chrome.runtime.openOptionsPage();를 하면 
Uncaught TypeError: chrome.runtime.openOptionsPage is not a function
    at <anonymous>:1:16
이렇게 뜨네요ㅜㅜ

**Comment by smartwe** [comment]
아 option.html을 여는 코드 군요!

**Comment by joonas-yoon** [comment]
> 아 option.html을 여는 코드 군요!

네, extension 에서 실행할 수 있는 코드로, browser의 콘솔에서는 호출이 안 됩니다.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/openOptionsPage

**Comment by smartwe** [comment]
Electrin으로 앱을 만드는중인데 익스텐션 부분에서
설정부분만 에러가 나더라구요

**Comment by joonas-yoon** [comment]
아 그러면 그럴 수 있겠네요.

https://electronjs.org/docs/latest/api/extensions

확인해보니 `chrome.storage.sync` 도 지원하지 않고 있어서 이 부분도 문제가 될 수 있으니 참고하시면 좋겠습니다

**Comment by smartwe** [comment]
아 그부분은 해결했습니다!
