### ISSUE TITLE
`런타임 에러의 원인을 찾는 중` 이후 퍼센트 표시 오류

### ISSUE THREAD

**Issue by joonas-yoon** [joonas-yoon/boj-extended#78]
사소한 이슈지만, 제출 후에 런타임 에러가 발생하는 경우 런타임 에러의 원인을 찾는 중 (00%)이렇게 퍼센트가 올라가는데 이렇게 되면 무조건 100%까지 진행되었다가 틀린 것 처럼 보입니다.
![image](https://user-images.githubusercontent.com/44183313/152673286-d382a66c-590f-45fc-b1a6-78331e51a59a.png)
![image](https://user-images.githubusercontent.com/44183313/152673405-6bf0e404-1a08-49b5-a826-e187a8b5c4c5.png)

_Originally posted by @sion-k in https://github.com/joonas-yoon/boj-extended/issues/35#issuecomment-1030777054_

**Comment by joonas-yoon** [comment]
@sion-k 다른 문제에서 제출했을 때도 확인이 어렵고, 해당 문제도 2% 에서 틀리는 코드를 제출했는데도 확인이 안되네요.

혹시 **채점 번호**와 **제출하신 코드**를 알려주실 수 있을까요?

**Comment by sion-k** [comment]
https://www.acmicpc.net/source/share/8714f2c7b7654f8e8b6f960e9e5d0314
s 배열의 길이가 1000이라서 런타임 에러가 발생했습니다

**Comment by joonas-yoon** [comment]
@sion-k 저 이거 재현이 안되는데 음... 의심되는 부분을 최대한 수정해보도록 하겠습니다 ;;

**Comment by joonas-yoon** [comment]
오랜만에 다시 보니까 재현도 잘 되고 증상도 파악이 되어서 잘 수정했습니다~

![boj-rte-finding-fixed](https://user-images.githubusercontent.com/9527681/185526258-4292730f-a713-48a4-9f45-11ccd2c39d1b.gif)

1.8.3.3 버전에 반영될 예정입니다 :)

**Comment by joonas-yoon** [comment]
[1.8.4 버전](https://github.com/joonas-yoon/boj-extended/pull/108)에 반영되었습니다 🎉
