### ISSUE TITLE
일부 기능 오류 및 미지원 안내

### ISSUE THREAD

**Issue by joonas-yoon** [joonas-yoon/boj-extended#80]
**BOJ 공지 참고**
- https://www.acmicpc.net/board/view/85102

가장 크리티컬한 업데이트 내용은 아래입니다.

> 1˛ 방화벽 업데이트
> 
> BOJ의 방화벽 관련 업데이트를 했습니다. 이 업데이트는 2022-02-23, 2022-03-02 두 번 진행했습니다.
> ...
> 두 업데이트 모두 비정상적이라 판단되는 접근을 막는데 중점을 두었습니다. 업데이트 전에 봇으로 추정되는 트래픽이 전체 트래픽의 약 60-70% 정도를 차지했었습니다.
> 
> 이 업데이트로 인해 BOJ 유저가 만든 일부 익스텐션과 스크립트가 동작하지 않을 수도 있습니다.

　

구현 단계에서도 최소한으로 트래픽을 줄이고자 몇가지 방법들을 사용했으나, BOJ Extended 사용자가 최근 1천명 이상으로 늘어나면서 생각보다 많은 트래픽 증가를 유발시킨 것으로 보입니다.

BOJ에 영향을 주는 행위는 최소한으로 하고자 해서, 관련 기능들은 다시 부활하지 않을수도 있습니다.

　

**확인된 _동작하지 않는_ 기능은 아래와 같습니다.**

- 알림 페이지
- - ~문제 해결 여부(문제 색상) 표시가 되지 않고 있습니다.~
- - `1.7.6` 버전부터 제공되지 않습니다.
- 게시글 수 표시
- - ~문제 보기 화면에서 질문 게시글의 수가 표시되지 않고 있습니다.~
- - `1.7.6` 버전부터 제공되지 않습니다.
- 유저 문제 VS (https://github.com/joonas-yoon/boj-extended/issues/12)
- - `1.7.7` 버전부터 제공되지 않을 예정입니다.

　

감사합니다.

![thanks](https://c.tenor.com/mVt8g4gAAMQAAAAC/cat-hat-off.gif)

**Comment by Kredsya** [comment]
+ 추가로 프로필 화면에서 문제 제목으로 보기 기능이 작동하지 않고 있습니다.
![image](https://user-images.githubusercontent.com/47083922/158113008-ad70d699-7a05-410b-9061-d6b9af8cc99d.png)

**Comment by joonas-yoon** [comment]
@Kredsya 제보 감사합니다. 그건 버그 같은데 따로 이슈로 파겠습니다.

**Comment by joonas-yoon** [comment]
https://github.com/joonas-yoon/boj-extended/discussions/97 로 옮김
