### ISSUE TITLE
자신이 푼 문제 정렬 기능 추가 요청드립니다.

### ISSUE THREAD

**Issue by packkill** [joonas-yoon/boj-extended#85]
**내용**
 
자신이 푼 문제 중에서 다른 사람이 자신의 코드를 본 횟수를 숫자로 보여주고 정렬기능까지 있으면 좋겠습니다. 또한 숏코딩 랭킹도 정렬기능이 있으면 좋을거 같습니다.

 
숏코딩 평소에 종종 하게 되는데 몇개는 숏코딩 1등을 먹었지만 시간이 지나면서 숏코딩 1등을 먹었던 문제가 뭐였는지 까먹게 되더라고요. 이러한 이유 때문에 요청드립니다. 또한 내 코드들 중에서 어떤 코드를 사람들이 가장 많이 봤는지 궁금했는데 알아볼 방법이 없어서 기능요청드립니다.

자신이 푼 문제 정렬 기능 (숏코딩랭킹순으로)
자신이 푼 문제 정렬 기능 (코드가 읽혀진 횟수 순으로)

**Comment by joonas-yoon** [comment]
@packkill 안녕하세요, 해당 기능은 그룹 내 멤버 정렬처럼 **한 페이지에 모든 정보가 있지 않으면** 구현이 불가한 부분입니다.

각 유저들의 모든 문제 풀이 상태를 알아야해서, 스크래핑을 하지 않는 이상 BOJ에서 API 지원될 때까지 기다려야할 것 같습니다.

<br>

**# 다른 사람이 자신의 코드를 본 횟수 카운트** 

카운트하더라도 BOJ Extended 사용자만 카운트될텐데, 이 역시 수집하기위해서 별도의 서버가 필요하다보니 어렵습니다.

이건 원래 있었던 기능으로 아는데, 제 기억으로 약 5년 전에 없어진 기능이네요. 

기능 요청 남겨주셔서 감사합니다.

**Comment by joonas-yoon** [comment]
이슈는 닫겠습니다!!
