### ISSUE TITLE
그룹에서 문제집 URL 수정

### ISSUE THREAD

**Issue by pizzaroot** [joonas-yoon/boj-extended#86]
**내용**

그룹에서 문제집을 클릭했을 때
group/workbook/list/id가 아닌
group/workbook/id로 가야할것 같습니다!

**환경**

 - Browser: Chrome
 - OS: Windows 10
 - Architecture:
 - App version: (설치되어있는 boj-extended 확장 프로그램 버전)

**Comment by joonas-yoon** [comment]
제보 감사합니다! 업데이트가 있었군요: https://www.acmicpc.net/board/view/88350

**Comment by joonas-yoon** [comment]
`1.7.8.1` 버전으로 배포되었습니다.
