### ISSUE TITLE
RIGEL / 어두운 테마 사용 시 새로운 페이지를 로드할 때마다 하얗게 번쩍임

### ISSUE THREAD

**Issue by BamgoeSN** [joonas-yoon/boj-extended#90]
**내용**

[영상(유튜브)](https://youtu.be/TBrzkJPvHk0)
테마를 RIGEL 또는 어두운 테마로 설정하면, 새로운 페이지를 로드할 때마다 매우 짧은 시간동안 밝은 테마로 바뀌었다가 다시 돌아오는데, 매우 눈이 아픕니다.
2~3일 전부터 이런 현상이 발생했습니다.
위 영상은 노트북에서 녹화한 거지만, Windows 10에서 돌아가는 데스크톱에서도 같은 현상이 발생합니다.

**환경**

노트북
 - Browser: Chrome - Version 101.0.4951.54 (Official Build) (64-bit)
 - OS: Ubuntu 22.04 LTS
 - Architecture: x86-64
 - App version: 1.8.0

데스크탑
 - Browser: Chrome - Version 101.0.4951.54 (Official Build) (64-bit)
 - OS: 10.0.19044.1645
 - Architecture: x86-64
 - App version: 1.8.0

데스크탑에서 제시하신 커맨드를 붙여넣었을 때 아래와 같은 결과와 함께 정상적으로 실행되지 않아, 아키텍쳐는 제가 아는대로 적었습니다.
```
C:\Users\bamgoesn> Architecture: $((Get-AppxPackage -Name Microsoft.WindowsCalculator).Architecture)
Get-AppxPackage: The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
Architecture:: The term 'Architecture:' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
C:\Users\bamgoesn> Import-Module Appx
Import-Module: Operation is not supported on this platform. (0x80131539)
```

**Comment by joonas-yoon** [comment]
@BamgoeSN 안녕하세요 저도 다른 컴퓨터에서 동일 현상 발견하고 버전 내리려고 왔는데 이렇게 먼저 이슈 남겨주신 것을 발견했네요 ㅠㅠ 

변경사항은 1.7.8.1 버전으로 다시 롤백하고, 안정적으로 동작하는 것 확인되면 다시 업데이트 하도록 하겠습니다.

이슈를 자세하게 적어주셔서 정말 감사합니다!!

**Comment by joonas-yoon** [comment]
1.8.1 버전으로 배포 완료하였고, (경험상) 수분내로 웹 스토어와 크롬 브라우저에 적용될 예정입니다.

업데이트가 자동으로 되지 않는다면 `브라우저의 설정 - 확장 프로그램 - 업데이트` 로 업데이트하실 수 있습니다.

감사합니다.
