### ISSUE TITLE
Electron에서 테마가 로드되지 않음

### ISSUE THREAD

**Issue by smartwe** [joonas-yoon/boj-extended#98]
<img width="1509" alt="스크린샷 2022-08-13 01 42 38" src="https://user-images.githubusercontent.com/73765768/184404932-fd336e4a-3424-4049-a2a3-b30b4109be29.png">
여기에서 테마 불러오는 중... 이라고 계속 뜨네요

**Comment by joonas-yoon** [comment]
환경이 어떻게 되나요? 사용하시는 버전이 몇인지 적어주시면 해결이 더 빠를 것 같습니다.

```
**환경**
<!--- Windows 버전, 사용하시는 브라우저와 버전 (Chrome/95.0.4638.69) 등 -->
 - Browser:
 - OS:
 - Architecture:
 - App version: (설치되어있는 boj-extended 확장 프로그램 버전)
<!--
Windows의 경우, PowerShell 에서 아래 커맨드를 복사/붙여넣기한 결과를 적어주세요.
" - OS: $([Environment]::OSVersion.Version)"
" - Architecture: $((Get-AppxPackage -Name Microsoft.WindowsCalculator).Architecture)"
```

**Comment by smartwe** [comment]
브라우저는 Chromium 104.0.5112.65
환경은 electron 20.0.0
OS는 mac
Architecture은 arm64

**Comment by joonas-yoon** [comment]
확인 감사합니다. 크로미움이라면 "설정 > 확장 프로그램 관리"에서 보이는 BOJ Extended 버전도 혹시 알 수 있을까요?

최신 버전에서 발생하는 버그인지 확인하고 싶어서요

**Comment by smartwe** [comment]
버전은 1.8.1입니당

**Comment by smartwe** [comment]
혹시 확장프로그램에서 chrome 스토리지 사용하나요?

**Comment by joonas-yoon** [comment]
> 혹시 확장프로그램에서 chrome 스토리지 사용하나요?

엇 네 맞아요. 로컬에서 이걸 사용하지 않는 설정이 있나요??

**Comment by smartwe** [comment]
혹시 그 크롬 스토리지를 사용하는 기능이 1.7.5.1 버전에서 없었나요?

**Comment by joonas-yoon** [comment]
아뇨.. 가장 첫 버전인 1.0.0 버전부터 있었습니다.

https://github.com/joonas-yoon/boj-extended/blob/main/UPDATENOTE.md#v100

지금까지 크롬 스토어에서 설치하셔서 사용하신 분 중 macOS 비율이 20% 정도 됩니다. 저도 어떤 게 원인인지를 파악하기가 어렵네요 음....

**Comment by smartwe** [comment]
제가 크롬에서도 boj-extended를 사용하는데 문제가 없거든요
그럼 electron.js에서 뭔가 문제가 있는것 같네요
근데 의문인점은 1.7.5.1 버전은 멀쩡히 로딩이 되네요

**Comment by joonas-yoon** [comment]
🤔 음.. 1.8.1 버전은 1.7.6 버전으로 되돌리는 게 전부인데, 그럼 1.7.6 버전 변경을 살펴봐야겠군요.

**Comment by smartwe** [comment]
ㅎㅎ 그런가요?
봐주셔서 감사합니다👍

**Comment by smartwe** [comment]
그런데 이젠  
 OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed
  ID:      fndenjmnddkjnmkhpkgldpcebkilampg
  Type:    ManifestError
[95682:0814/234442.826941:ERROR:service_worker_storage.cc(1904)] Failed to delete the database: Database IO error
이런 에러가 나네요

**Comment by getCurrentThread** [comment]
@joonas-yoon manifest.json에 **unlimitedStorage** 권한을 추가해보시는 건 어떨까요.
저장 데이터가 그렇게 많지 않아서 일어나지 않을 것으로 여기긴 하였는데, 이 구간 밖에는 의심되는 영역이 없네요.

**Comment by smartwe** [comment]
넵

**Comment by joonas-yoon** [comment]
@getCurrentThread 오... 항목당 4KB 제한이 있는 줄은 덕분에 처음 알았네요. 감사합니다.

우선 이슈 파악에 도움이 될 수 있을 것 같아서 기록으로 코멘트를 남겨보겠습니다.

https://github.com/joonas-yoon/boj-extended/blob/release/js/background.js#L5-L19

지금은 구조가 백그라운드에서 설정 객체를 따로 가지고 있고, 실제 `storage.sync`를 가져오기 이전에 메모리에 key-value dict를 두어서 storage에 접근하기 전의 버퍼 역할을 하고 있습니다.

그리고 모든 설정은 한 항목으로 저장되고 있습니다.

그래서 서비스 워커에 찍히는 로그를 확인해봐야할 것 같습니다 흠...

**Comment by joonas-yoon** [comment]
아!! 채점 현황에 표시되던 항목들(`채점 중 (00%)`)이 4KB를 넘길 수 있겠네요.. 이거 어떻게 할까 생각하다가 잊고 있었네요.

만약에 브라우저 캐시랑 로컬 스토리지를 비웠는데도 반복된다면, 이 문제가 맞을 것 같습니다.

**Comment by getCurrentThread** [comment]
@joonas-yoon 해당 이슈와 다른 건인데, 풀리퀘도 확인 부탁드릴께요!

**Comment by joonas-yoon** [comment]
@getCurrentThread 네 물론이죠 ㅎㅎ 확인하고 있었습니다

**Comment by smartwe** [comment]
혹시 이걸 쓰나요? chrome.storage.sync

**Comment by joonas-yoon** [comment]
네 맞습니다. 그 부분은 해결되신것 아니었나요?

https://github.com/joonas-yoon/boj-extended/issues/76#issuecomment-1036990434

**Comment by smartwe** [comment]
그게 오류의 이유를 생각해보는 중인데 전버전은 됬었으니까 아닌것 같아요

**Comment by smartwe** [comment]
수정해서 정상 작동합니다 감사합니다
